### ISSUE TITLE
多机自动同步失败

### ISSUE THREAD

**Issue by Rain168** [sjqzhang/go-fastdfs#1]
"peers": ["http://127.0.0.1:8080","http://127.0.0.1:8081","http://127.0.0.1:8082"],
我是这样设置的，不知道是不是有问题？ 请指正，谢谢

**Comment by sjqzhang** [comment]
在设计之初就已考虑到集群的高可用问题，为了保证集群的真正可用，集群不同部署在同一个ＩＰ下，必须为不同的ＩＰ

**Comment by sjqzhang** [comment]
> "peers": ["http://127.0.0.1:8080","http://127.0.0.1:8081","http://127.0.0.1:8082"],
> 我是这样设置的，不知道是不是有问题？ 请指正，谢谢
