### ISSUE TITLE
集群图片更新问题

### ISSUE THREAD

**Issue by yeaze** [sjqzhang/go-fastdfs#100]
问题描述：现有机器A(192.168.49.1)和B(192/168.49.2) 组成集群
1、先在机器A上传一张图片photo.png，并且指定path，假设上传后的图片地址为：http://192.168.49.1:8080/group1/image/photo.png
2、此时在机器B上访问:http://192.168.49.2:8080/group1/image/photo.png，可以正常访问到图片。
3、接着我在机器B上，再次上传一张图片（文件名依然是photo.png,但是图片不是同一张，并且指定的path和第一步上传时的相同，可以理解成我要更新一下之前上传的图片）。
4、在机器B访问：http://192.168.49.2:8080/group1/image/photo.png，可以看到图片内容已经更新了。
5、回到机器A访问：http://192.168.49.1:8080/group1/image/photo.png 发现此时图片并没有被更新，依然是最开始上传的图片。现在机器A和B上的图片已经不一致了，不会同步更新。

**Comment by sjqzhang** [comment]
请用最新版本验证

**Comment by yeaze** [comment]
上述的实验结果就是基于最新版本的，同时enable_distinct_file已经设置为false了。
