### ISSUE TITLE
请问你的ldb主要做什么用处的呢？

### ISSUE THREAD

**Issue by hanzhihua** [sjqzhang/go-fastdfs#102]
谢谢你的快速回答:)
请问你的ldb主要做什么用处的呢？
你的存储结构跟fastdfs好像不太一样，就是目录结构

**Comment by sjqzhang** [comment]
存储元数据，名称需叫fastdfs，两者区别还是很大的.

**Comment by hanzhihua** [comment]
嗯，拜读一下大作，准备用你这个产品，对了这个机器的规模是不是就是一个机器的容量呢
