### ISSUE TITLE
kubernetes部署

### ISSUE THREAD

**Issue by cwocwo** [sjqzhang/go-fastdfs#105]
我想要Kubernetes部署 go-fastdfs，Kubernetes本身有个代理，还需要nginx吗？

**Comment by sjqzhang** [comment]
建议线上还是保留nginx，因为nginx还可以增强很多功能，go-fastdfs只提供了文件存储功能。

**Comment by cwocwo** [comment]
Kubernetes中使用statefulset部署，发现多个副本之间文件不能同步

**Comment by happyHeartJ** [comment]
> Kubernetes中使用statefulset部署，发现多个副本之间文件不能同步

请问这个问题最后解决了吗？

**Comment by cwocwo** [comment]
解决了， 你遇到问题了吗？

**Comment by dazuimao1990** [comment]
> 解决了， 你遇到问题了吗？

请教几个问题：
1. 在 K8s 中使用 statefulset 进行集群部署， Peers 参数怎么制定？IP 会变化
2. 多个副本之间的同步问题是怎么解决的？
