### ISSUE TITLE
当跨域与验证auth_token都使用时上传问题

### ISSUE THREAD

**Issue by tettyqwer** [sjqzhang/go-fastdfs#106]
当跨域使用并且打开auth_token验证的时候，某些情况浏览器会发送options请求，参考：
[https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS#Preflighted_requests](url)

但这个options请求进入upload方法后，会触发验证auth_token，但这时候是没有参数的，所以导致验证出错。fileserver.go(2141行)是不是要先判断一下请求类型，再调用验证？

**Comment by sjqzhang** [comment]
那需要返回什么呢？

**Comment by sjqzhang** [comment]
我已经提交了一版，你自已测试一下看是否满足你的需求。

**Comment by tettyqwer** [comment]
> 那需要返回什么呢？

options主要是使用http header 一般不会用到返回内容

**Comment by tettyqwer** [comment]
> 我已经提交了一版，你自已测试一下看是否满足你的需求。

测试过已经可用了，非常感谢！
