### ISSUE TITLE
使用NGINX做负载均衡，如何避免存储节点满后无法继续存储问题？

### ISSUE THREAD

**Issue by beanhacker** [sjqzhang/go-fastdfs#108]
大神，咨询个问题：
   使用NGINX做负载均衡，如何避免存储节点满后无法继续存储问题？
   我理解NGINX的负载均衡，只能解决工作资源占用不均问题，如果一个存储节点已满，即使响应很快，也无法继续接受存储，这就导致NGINX给分配的资源其实是不可用的，除非这个节点可以做数据接力，在自身无能力时，充当中间人角色，向其他节点轮询和转发数据。

**Comment by sjqzhang** [comment]
参阅 https://sjqzhang.github.io/go-fastdfs/install.html#big-cluster

**Comment by beanhacker** [comment]
不觉得解决这个问题，请大神点拨
