### ISSUE TITLE
后续是否可能兼容S3接口？

### ISSUE THREAD

**Issue by henrythefool** [sjqzhang/go-fastdfs#109]
之所以这么问，
一方面，项目之前是用S3，想切过来，配套的设施得重写。
另一方面，感觉S3已经成为了对象存储的标准，选S3以外的方案，好像不太符合发展趋势，在这个项目和Minio之间有点犹豫。
未来有没有可能支持S3接口？

**Comment by sjqzhang** [comment]
你说的对，S3目前的确是对象存储的标准，本项目底层是用kv存储元数据，与对象存储的结构是一致的，所以从技术上看完全没问题，由于本人没实际使用s3，对它的理解可能是片面的，希望这个由比较熟悉s3的同学来完成，或者提供go版本的s3接口让我考虑考虑，长远来说s3 应该被支持，只是时间问题。

**Comment by sjqzhang** [comment]
https://github.com/not-nexus/shelf/blob/master/docs/api/artifact.md   不知这个是不是完整的s3接口中，如果是完整的，那完全可以是可以有的。只不过使用了go-fastdfs自定义路径功能,有使用s3经验的可以看看是不是一样的。

s3 upload
```
 curl -v -i -L -H "Authorization: supersecuretoken" -F "file=@./upload-test.txt" localhost:8080/bucket-name/artifact/upload-test.txt
```

go-fastdfs upload
```
 curl -v -i -L -H "Authorization: supersecuretoken" -F "file=@./upload-test.txt" localhost:8080/groupname/upload
```
s3 download
```
curl -i -L -H "Authorization: supersecuretoken" localhost:8080/bucket-name/artifact/hello-world > hello-world.txt
```

go-fastfds download
```
curl -i -L -H "Authorization: supersecuretoken" localhost:8080/groupname/artifact/hello-world > hello-world.txt
```

**Comment by henrythefool** [comment]
可以参考Minio，它是用Go写的，完全兼容S3，创始人是Gluster的作者。
而且Minio还有一系列的开源配套客户端。
我们之前用过一阵Minio，好处是完全兼容各种S3的SDK和API，但感觉在某些场景下性能有点问题。

**Comment by sjqzhang** [comment]
希望有熟悉s3,并且熟悉go-fastdfs 的同学加入
