### ISSUE TITLE
关于download_domain配置，需要使用https的问题

### ISSUE THREAD

**Issue by tettyqwer** [sjqzhang/go-fastdfs#115]
"下载域名": "用于外网下载文件的域名,不包含http://"
"download_domain": ""
当需要使用https域名下载链接的时候，这里无法满足需求，代码里写死了只返回http链接fileserver.go (2031行) ；是否可以实现多一个配置使用https?

**Comment by sjqzhang** [comment]
下一版本考虑兼容https返回
