### ISSUE TITLE
请问下提供的http client包是否可以支持长连接

### ISSUE THREAD

**Issue by gmxdja** [sjqzhang/go-fastdfs#117]
http上传下载方式，当文件一直续传时，每次建立TCP连接，比较浪费资源，是不是可以支持长连接方式，省去握手的机制呢，麻烦回答一下，感激不尽

**Comment by sjqzhang** [comment]
如果对于实时消息,你的需求非常合理,但对于文件感觉这是一个伪需求.

原因:文件一般较大,建立连接一般100ms以内,对于文件传输时间来说,小太多,另外不断传文件的场景非常少
