### ISSUE TITLE
docker 服务重启后重置所有文件

### ISSUE THREAD

**Issue by ljy-shiwode** [sjqzhang/go-fastdfs#121]
docker 服务重启后重置所有文件,

**Comment by sjqzhang** [comment]
将数据挂载到宿主机的磁盘上以持久化

**Comment by ljy-shiwode** [comment]
没描述清除，是宿主机重启后文件被重置；因为刚接触docker有些东西不太清楚， 文件挂在到宿主机上了也； 谢谢


------------------ 原始邮件 ------------------
发件人: "小张"<notifications@github.com>;
发送时间: 2019年9月27日(星期五) 中午11:03
收件人: "sjqzhang/go-fastdfs"<go-fastdfs@noreply.github.com>;
抄送: "1294522073"<1294522073@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sjqzhang/go-fastdfs] docker 服务重启后重置所有文件 (#121)




将数据挂载到宿主机的磁盘上以持久化
