### ISSUE TITLE
stat接口能否添加返回磁盘总容量的信息？

### ISSUE THREAD

**Issue by 694551594** [sjqzhang/go-fastdfs#123]
因为要涉及到磁盘预警的功能，所以需要知道磁盘剩余容量的信息，我看了下stat接口现在可以返回已经使用的容量，但是没有总容量或者剩余容量。请问下是否可以添加。

**Comment by sjqzhang** [comment]
下个版本增加内存，磁盘信息到status接口中，请关注下一版本发布

**Comment by sjqzhang** [comment]
己在v1.3.4版本支持
