### ISSUE TITLE
文件下载设置的文件类型头有问题

### ISSUE THREAD

**Issue by ljyf5593** [sjqzhang/go-fastdfs#127]
因为文件下载时使用的文件下载头全部设置的
`w.Header().Set("Content-Type", "application/octet-stream")`
这样导致IE浏览器在下载 `docx  xlsx pptx`等文件时，会因为检测不到正确的文件类型，而全部是后缀为.zip的文件

**Comment by sjqzhang** [comment]
浏览器会改后缀？

**Comment by ljyf5593** [comment]
是的，会改后缀  https://blog.csdn.net/loonie51/article/details/20481721 参考

**Comment by GanHuaLin** [comment]
请问下改怎么解决这个问题，我也遇到了！
微信小程序里下载doc、docx文件，后缀是.zip
