### ISSUE TITLE
通用校验希望能获取文件路径，用户颗粒化权限校验？

### ISSUE THREAD

**Issue by MRchao90s** [sjqzhang/go-fastdfs#128]
如图所示
![image](https://user-images.githubusercontent.com/25077986/66797621-f725bd80-ef3d-11e9-81b0-0c95d9d2de66.png)

**Comment by sjqzhang** [comment]
后面可以增另一个原URL参数，给业务方去解释使用

**Comment by sjqzhang** [comment]
已加入  __path__ ,__query__参数，可以在v1.3.5版本中使用
