### ISSUE TITLE
使用hutool的http工具进行上传时，返回request Content-Type isn't multipart/form-data

### ISSUE THREAD

**Issue by jethrozz** [sjqzhang/go-fastdfs#129]
按照文档上的代码使用hutool进行http上传，但是给我返回这个提示
request Content-Type isn't multipart/form-data

下面是代码：
`        byte[] bytes = FileUtil.readBytes(filePath);
        File file = new File(filePath);

        InputStream inputStream = new ByteArrayInputStream(bytes);
        InputStreamResource isr = new InputStreamResource(inputStream, file.getName());
       

        //声明参数集合
        HashMap<String, Object> paramMap = new HashMap<String, Object>();
        //文件
        paramMap.put("file", isr);
        //输出
        paramMap.put("output", "json");
        //自定义路径
        //paramMap.put("path", "image");
        //场景
        paramMap.put("scene", "register");
        //上传
        String result = HttpUtil.post(MessageFormat.format("{0}/upload", address), paramMap);`

使用okhttp3进行上传（代码复制的文档中的示例代码）时，有时候正常，有时候提示

(String)"(error) if you want to upload fast md5 is require,and if you want to upload file,you must use post method 

想问下这个情况的大概原因

**Comment by sjqzhang** [comment]
用http方法错了要post，看示例

**Comment by jethrozz** [comment]
不好意思，我没有粘贴okhttp3的代码，因为是直接复制的文档上的代码。下面我把代码贴出来。
` OkHttpClient httpClient = new OkHttpClient();
            MultipartBody multipartBody = new MultipartBody.Builder().
                    setType(MultipartBody.FORM)
                    .addFormDataPart("file", UUIDTool.newUUID() +".jpg",
                            okhttp3.RequestBody.create(MediaType.parse("multipart/form-data;charset=utf-8"),
                                    isr))
                    .addFormDataPart("output", "json")
                    .addFormDataPart("path","xmship")
                    .addFormDataPart("scene","face")
                    .build();

            Request request = new Request.Builder()
                    .url(uploadImgUrl+"/upload")
                    .post(multipartBody)
                    .build();
            Response response = httpClient.newCall(request).execute();`

这个有时候正常，有时候返回上述的提示。

**Comment by chuangtim** [comment]
> 按照文档上的代码使用hutool进行http上传，但是给我返回这个提示
> request Content-Type isn't multipart/form-data
> 
> 下面是代码：
> ` byte[] bytes = FileUtil.readBytes(filePath);
> File file = new File(filePath);
> 
> ```
>     InputStream inputStream = new ByteArrayInputStream(bytes);
>     InputStreamResource isr = new InputStreamResource(inputStream, file.getName());
>    
> 
>     //声明参数集合
>     HashMap<String, Object> paramMap = new HashMap<String, Object>();
>     //文件
>     paramMap.put("file", isr);
>     //输出
>     paramMap.put("output", "json");
>     //自定义路径
>     //paramMap.put("path", "image");
>     //场景
>     paramMap.put("scene", "register");
>     //上传
>     String result = HttpUtil.post(MessageFormat.format("{0}/upload", address), paramMap);`
> ```
> 
> 使用okhttp3进行上传（代码复制的文档中的示例代码）时，有时候正常，有时候提示
> 
> (String)"(error) if you want to upload fast md5 is require,and if you want to upload file,you must use post method
> 
> 想问下这个情况的大概原因

好像我也遇到这种情况，安装文档上传出现**request Content-Type isn't multipart/form-data**

**Comment by karry2019** [comment]
去掉url 中多余的 斜杆， 试试
