### ISSUE TITLE
有问题如何快速解决？

### ISSUE THREAD

**Issue by sjqzhang** [sjqzhang/go-fastdfs#13]
大家有问题时，解决办法：
一、先阅读一下QA
二、看一下已关闭的issue 有没有相关的回答
，如果请扫描帮忙文档Q&A二维码。

![二维码](https://raw.githubusercontent.com/sjqzhang/go-fastdfs/master/doc/wechat.jpg)

**Comment by zoucunjie** [comment]
google 认证码部分， 白名单存在请求的IP，但是无效 另在API文档部分 能不能详细到http方法 以及 可否将API部分 浏览器也支持上方面 测试 就例如获取google认证码

**Comment by chenhj520** [comment]
最近公司进行安可测试
项目中使用go-fastdfs 
下载源码可以编译成功，但是执行的时候提示
  cannot execute binary file

查看go环境变量信息
>go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_arm64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build229346615=/tmp/go-build -gno-record-gcc-switches"

修改build.sh 
GOARCH=amd64  改为与go环境变量中GOARCH值，如下
GOPATH=`pwd` GOOS=linux GOARCH=arm64  go build -o fileserver 

重新编译，解决！


参考：
https://stackoverflow.com/questions/36198418/golang-cannot-execute-binary-file-exec-format-error

**Comment by EricLongLiu** [comment]
使用go-fastdfs管理文件时，直接从硬盘删除了文件，再上传相同文件时返回了删除过的路径，文件并没有真实上传，查询文件列表也不存在对应文件，应该怎么解决？
例如：go-fastdfs有对应路径/A/A.txt文件，我直接从硬盘删除A.txt文件，重新上传到/B路径下，返回的结果还是/A/A.txt，但是查询文件列表并不存在/A/A.txt或者/B/A.txt文件
