### ISSUE TITLE
是否可以增加取图片的一部分的功能

### ISSUE THREAD

**Issue by sunkainj** [sjqzhang/go-fastdfs#131]
在图片识别时常常会有很多结构化数据，记录了图片某一部分的数据，是否可以在读取图片时增加两个参数，x,y,类似这样的http://ip:8080/ivl/web/50f75c8ddb8cab191db1797b2bbbd0db.jpg?width=400&height=200&x=150&y=270,用来取出横坐标200像素，纵坐标270像素为起点，宽400高200位置的图片

**Comment by sjqzhang** [comment]
这个功能在企业版本中有，开源版本暂不支持。
