### ISSUE TITLE
请问在文件上传时http请求中Content-Type支持几种格式

### ISSUE THREAD

**Issue by guiyangLi** [sjqzhang/go-fastdfs#132]

**Comment by sjqzhang** [comment]
没用content-tpye做标识，只用http参数做为标识，text、json看内置web上传页面

**Comment by guiyangLi** [comment]
content-tpye不就是http参数吗？我之所以会问这个问题，我是发现当我在C++中组织Http请求头、请求体时，指定未application/json，服务器压根没有任何回应，连接都建立不了。

**Comment by guiyangLi** [comment]
content-tpye不就是http参数吗？我之所以会问这个问题，我是发现当我在C++中组织Http请求头、请求体时，指定为application/json，服务器压根没有任何回应，连接都建立不了。

**Comment by guiyangLi** [comment]
> 没用content-tpye做标识，只用http参数做为标识，text，json看内置web上传页面

content-tpye不就是http参数吗？我之所以会问这个问题，我是发现当我在C++中组织Http请求头、请求体时，指定为application/json，服务器压根没有任何回应，连接都建立不了。
