### ISSUE TITLE
上传重复文件（同名同路径）时报错

### ISSUE THREAD

**Issue by satbirdd** [sjqzhang/go-fastdfs#134]
gofastdfs指定路径上传重复文件（同名同路径）时报错，open files/cases/0_./uploads/node-v10.16.3.tar.gz.2: no such file or directory, err: [<nil>]
制定的路径为:cases
在服务器上保存上传文件的位置，手动创建目录files/cases/0_./uploads，可以消除这个错误，但是正确的解决方法是什么？

**Comment by sjqzhang** [comment]
用自带的web页面验证

**Comment by satbirdd** [comment]
现已证实是上传的file/filename参数带了路径引起的:
./uploads/node-v10.16.3.tar.gz.2
