### ISSUE TITLE
断点续传怎么配置scene等信息？

### ISSUE THREAD

**Issue by yangyongbin89** [sjqzhang/go-fastdfs#145]
您好，go-fastdfs的开发者们，我很喜欢go-fastdfs，风格很简洁。但我学习上遇到到棘手的问题，断点续传怎么配置scene等信息？还有为什么断点续传和普通上传不能做成一个接口？期待您们的回答，感谢您们的勤劳付出。

**Comment by sjqzhang** [comment]
断点续传暂不支持scene，两者协议不太一样，并在一起使用应该也不好用
