### ISSUE TITLE
临时文件清理、配置文件格式、安全退出程序问题

### ISSUE THREAD

**Issue by chaoweiyi** [sjqzhang/go-fastdfs#151]
你好，最近测试，有几个问题比较困惑
（1）files -> _tmp、log，目录内文件是否自动清理，多久清理一次
（2）配置文件是否可以兼容ini或yml格式，主要是注释在json内不好阅读
（3）目前实现自动启动程序，重启时，是否有同nginx一样的，命令行参数，可以安全退出程序

谢谢！

**Comment by sjqzhang** [comment]
1、log 滚动写，_tmp上传完文件，实时清理
2、不会支持其它格式，可以手动删除注释，或调用api  reload一下注释就会自动删除
3、后面的版本支持
