### ISSUE TITLE
go-fastdfs自己关掉进程

### ISSUE THREAD

**Issue by onedoginhouse** [sjqzhang/go-fastdfs#156]
大哥有没有碰到go-fastdfs部署到云服务器上  然后无故自己进程关掉的情况.

之前考虑可能是安全组中将本服务器的ip排除在外  导致dial超时的可能 就把服务器的ip加到安全组里面了  但是 后来进程还是自己关掉了  log里面也没有提示

**Comment by sjqzhang** [comment]
没放到后台运行。

**Comment by onedoginhouse** [comment]
> 没放到后台运行。

嗯 是这个问题  解决方法文档里有  多谢
