### ISSUE TITLE
使用hutool实现管理API

### ISSUE THREAD

**Issue by WingedCat** [sjqzhang/go-fastdfs#158]
使用hutool实现管理API，结果不是http:no such file就提示Content-Type isn't multipart/form-data。如何解决。比如先这段代码是文件秒传这一API。
        String resp = "";
        Map<String,Object> params = new HashMap<>();
        params.put("md5",md5);
        params.put("output", "json");
        if(StringUtils.isBlank(groupName)){
            resp = HttpUtil.post(GO_FASTDFS_URL+GROUPNAME+"/upload",params);
        }else{
            resp = HttpUtil.post(GO_FASTDFS_URL+groupName+"/upload",params);
        }

**Comment by sjqzhang** [comment]
秒传用http get，卡传用http post，此设计用起来不方便。
