### ISSUE TITLE
'https://github.com/belogik/goes/' not found

### ISSUE THREAD

**Issue by ghostx01** [sjqzhang/go-fastdfs#161]
go: finding github.com/belogik/goes v0.0.0-20151229125003-e54d722c3aff
go: github.com/belogik/goes@v0.0.0-20151229125003-e54d722c3aff: git fetch -f https://github.com/belogik/goes refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in D:\mygo\pkg\mod\cache\vcs\5b0453a6aac74c86b31f0a771f02325d031eaf6ec0f0503f1cc20852de3abb0a: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/belogik/goes/' not found
go: error loading module requirements

**Comment by ghostx01** [comment]
If I don't use go mod, it is normal now.

**Comment by sjqzhang** [comment]
项目没有使用go mod,需自行验证。
