### ISSUE TITLE
有关新版本reload api 报错问题

### ISSUE THREAD

**Issue by ypsliu** [sjqzhang/go-fastdfs#163]
我试了 curl http://127.0.0.1:8080/group1/reload?action=set&cfg=\\{'admin_ips': ['127.0.0.1','192.168.23.89']\\}
curl -X POST -d {"cfg":{"admin_ips": ["127.0.0.1","192.168.23.89"]}} http://127.0.0.1:8080/group1/reload?action=set 
都不行 
{
  "data": null,
  "message": "(error)parameter cfg(json) require",
  "status": "fail"
}
请问正确请求方式是

**Comment by sjqzhang** [comment]
修改配置文件，再调用action=reload
