### ISSUE TITLE
双机同步日志报错

### ISSUE THREAD

**Issue by jiandanfeng** [sjqzhang/go-fastdfs#170]
2020-02-10 14:10:08 [ERR] [fileserver.go:2935] [main.(*Server).AutoRepair.func1] json: cannot unmarshal object into Go value of type []main.StatDateFileInfo

请问下这个错误是什么原因？

**Comment by sjqzhang** [comment]
数据json反序列化出错，是最新版本么？正常流通应该不全受影响。

**Comment by jiandanfeng** [comment]
用的是docker hub上的image：
"RepoTags": [
            "sjqzhang/go-fastdfs:latest"
        ],
        "RepoDigests": [
            "sjqzhang/go-fastdfs@sha256:0aba16ddc27b5df3cd3d919b7e4af0ed8537e251202fa8d01de7d9ce46ec6a8c"
        ],
这个是最新的吗？还是最新的要自己build？
