### ISSUE TITLE
是否有mv命令类似的api？

### ISSUE THREAD

**Issue by pkaq** [sjqzhang/go-fastdfs#171]
跟 #73 担忧的事情相同， 目前是考虑上传时存储到路径为 /temp/date 的path下， 表单提交后 然后移动该文件到一个正式的目录，然后 temp/date 目录会在隔天后清理掉 

好像没有类似 mv 命令的 api？

**Comment by sjqzhang** [comment]
暂时没有

**Comment by pkaq** [comment]
有计划支持么
