### ISSUE TITLE
上传后返回的json中的url缺少端口，是否跟哪个地方配置有关。

### ISSUE THREAD

**Issue by jiandanfeng** [sjqzhang/go-fastdfs#174]
上传后跳转到的url：http://10.8.32.10:7772/group1/upload 
上传成功后返回的json：{"url":"http://10.8.32.10/group1/default/20200225/10/31/6/jb51.net.txt","md5":"1a84430e677616c4c4af9d8c52a70e8a","path":"/group1/default/20200225/10/31/6/jb51.net.txt","domain":"http://10.8.32.10","scene":"default","size":4848,"mtime":1582597911,"scenes":"default","retmsg":"","retcode":0,"src":"/group1/default/20200225/10/31/6/jb51.net.txt"}

我的端口是7772，但是返回的url不含有端口，导致访问不到

**Comment by sjqzhang** [comment]
有一个download_domain配置项，可以设置试试
