### ISSUE TITLE
请问自定义认证里面是否可以把自定义文件路径和文件名也带过去？

### ISSUE THREAD

**Issue by lsxredrain** [sjqzhang/go-fastdfs#177]
支持自定义认证的配置文件里面
"auth_url": "",的参数只带了 authtoken，是否可以把文件路径和文件名也作为参数带过去，这样我们在自定义鉴权系统里面可以对文件服务器的访问权限做访问控制，谢谢

**Comment by sjqzhang** [comment]
可以你，写在url后面就会带过去，你可以打印post参数看看。

**Comment by lsxredrain** [comment]
谢谢，
<<"filename=&path=&__path__=%2Fshapes%2Fupload&__query__=&auth_token=1111&submit=upload&scene=default&output=json&code=">>
已经打印出来了
