### ISSUE TITLE
自定义认证失败问题

### ISSUE THREAD

**Issue by k11hao** [sjqzhang/go-fastdfs#179]
在地址栏里面直接打开会认证失败,但是如果直接使用代码的方式下载就不去认证;
如下面的方式下去载
URLConnection url  = new URL("http://localhost:8081/group1/default/20200316/22/38/7/test.docx").openConnection();
        InputStream in = url.getInputStream();

        byte[] buffer = new byte[1024];
        int length = 0;
        FileOutputStream fos = new FileOutputStream(new File("/Users/oyjg/tmp/a.docx"));
        while ((length = in.read(buffer)) > 0) {
            fos.write(buffer, 0, length);
        }

**Comment by sjqzhang** [comment]
请认真看一下视频教程。

**Comment by k11hao** [comment]
好像问题找到了,因为我是在本机启动的文件服务,然后又在本机测试的,所以会跳过这个认证
![image](https://user-images.githubusercontent.com/6235692/76828487-0a75e580-685c-11ea-8445-3adb1ba77489.png)
