### ISSUE TITLE
配置项 default_download 不能及时生效问题

### ISSUE THREAD

**Issue by Takisu** [sjqzhang/go-fastdfs#183]
发现一种情况
1、当前配置项default_download 为false 即 文件浏览 模式时 ，修改 为 true 并将配置文件reload后，能够生效，  但是 当前default_download  为true 即 文件下载 模式时，切换 为浏览模式  再reload配置文件 后 却不能生效， 依旧是下载模式。 （简洁来说就是  浏览模式 切换能 下载模式能及时生效，反之 不能）  不知道是怎么回事

2. 这个go-fastdfs   怎么解决 例如 图片防盗链的问题，上传下载的时候能通过token 验证 ， 浏览的时候呢

**Comment by sjqzhang** [comment]
防盗链请参考nginx防盗链，不生效问题可能与浏览器机制有一点的关系。
