### ISSUE TITLE
关于配置管理API 请求参数格式

### ISSUE THREAD

**Issue by Takisu** [sjqzhang/go-fastdfs#184]
`http://10.1.5.9:8080/group/reload

参数：
action: set(修改参数),get获取参数,reload重新加载参数
cfg:json参数　与 action=set配合完成参数设置`

http://10.1.5.9:8080/group1/reload?action=set
cfg:json参数  这里到底该怎么传  form-data格式 不行 json格式也不行  例如修改 auth_url   能否给个postman 示例截图  辛苦

**Comment by sjqzhang** [comment]
类型:Form-data
方法:post
格式:json
其他自行测试验证

**Comment by waylon-gmail** [comment]
兄弟试出来了没有。没成功过一次，完全不知道参数怎么传。
{
  "data": null,
  "message": "(error)parameter cfg(json) require",
  "status": "fail"
}
