### ISSUE TITLE
支持集群自动清理维护特性

### ISSUE THREAD

**Issue by liuguijunhao** [sjqzhang/go-fastdfs#186]
是否有支持集群自动清理维护特性的开发计划？
为了满足服务器长期高可用而不必手动维护，可以根据配置开启以下特性：
  1、支持按空间最大容量百分比清理早期文件
  2、支持按文件最长有效期时间清理早期文件
当前最新版本测试情况，如果后台直接使用维护命令删除files下的过期文件，前台再使用api接口获取被删除文件时，会触发文件同步导致cpu内存占用高，而前台调用长期获取不到结果的问题。

**Comment by sjqzhang** [comment]
文件有效期在企业版本中有支持。
