### ISSUE TITLE
windows版的gofast_web如何启动，运行start后，浏览器上需要输入什么地址？输入192.168.1.242:8088不能访问，输入localhost:8088转到安装页面，需要填写gofast的账号，关键是我现在还没有账号。

### ISSUE THREAD

**Issue by xia349942714** [sjqzhang/go-fastdfs#188]

**Comment by jiandanfeng** [comment]
安装页面就是用来初始化账号的

**Comment by xia349942714** [comment]
您好，安装页面提示检查服务地址是否已配置白名单，是需要给服务器配置我客户端主机的ip地址吗,把我客户端主机的ip地址添加到服务器的白名单里？那服务端配置白名单是怎样操作的？烦请告知一下，不胜感激。另外，我发现网上有2套gofastdfs安装教程，都是你们的吗？



在 2020-03-30 14:11:07，"jiandanfeng" <notifications@github.com> 写道：

安装页面就是用来初始化账号的

**Comment by sjqzhang** [comment]
安装页面就是用来初始化账号的

**Comment by xia349942714** [comment]
谢谢回复，我已经装好了。
















在 2020-04-09 15:01:10，"小张" <notifications@github.com> 写道：

Closed #188.

**Comment by AzraelJi** [comment]
> 您好，安装页面提示检查服务地址是否已配置白名单，是需要给服务器配置我客户端主机的ip地址吗,把我客户端主机的ip地址添加到服务器的白名单里？那服务端配置白名单是怎样操作的？烦请告知一下，不胜感激。另外，我发现网上有2套gofastdfs安装教程，都是你们的吗？ 在 2020-03-30 14:11:07，"jiandanfeng" <notifications@github.com> 写道： 安装页面就是用来初始化账号的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by AzraelJi** [comment]
> 您好，安装页面提示检查服务地址是否已配置白名单，是需要给服务器配置我客户端主机的ip地址吗,把我客户端主机的ip地址添加到服务器的白名单里？那服务端配置白名单是怎样操作的？烦请告知一下，不胜感激。另外，我发现网上有2套gofastdfs安装教程，都是你们的吗？ 在 2020-03-30 14:11:07，"jiandanfeng" <notifications@github.com> 写道： 安装页面就是用来初始化账号的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好！我也遇到了同样的问题，是在gofastdfs配置文件哪里加客户端的ip地址呢？加了一个不行，求问！！！
