### ISSUE TITLE
生产上使用go-fastdfs的公司名称统计

### ISSUE THREAD

**Issue by zhangleijie** [sjqzhang/go-fastdfs#189]
楼主你好， 问下生产环境下都有那些公司在使用， 有统计过吗？

**Comment by sjqzhang** [comment]
具体没有统计过，据私信我的，线上大于100TB的不少于15家，在这里请大家自报一下线上使用本分布文件系统的公司名称。

**Comment by sjqzhang** [comment]
很多都是私聊的，从私聊我的记录看不少于15家100T的公司在使用，有几家是使用企业版本。
