### ISSUE TITLE
新增磁盘和集群扩容问题咨询

### ISSUE THREAD

**Issue by zhangleijie** [sjqzhang/go-fastdfs#190]
楼主你好， 有2个问题请教下。
问题1： 单机情况下磁盘空间不足新增加磁盘，新加的磁盘挂载到跟路径下的某个文件夹下；我本地看了下发现数据都是存储到/go-fastdfs/files/default目录下、  数据都存储到了files文件夹下，  在conf文件夹下的cfg.json文件中也没有看到可以配置新加磁盘的存储属性，我需要把我的数据存储到新加的磁盘中；
期望的一个友好配置方式为store_path=/store1，/store2，/store3 每一个文件夹就是一块磁盘, 可以用逗号来追加。如果/store1满以后， 自动往/store2 或者/store3 中存储 当然这个地方可以有一个合适的算法.
问题2：集群环境下扩容成本，您看下我的理解对不对
通常情况下满足冗余存储的成本是2n， 如果集群是n个节点，那么我的存储成本就是nn;
go-fastdfs 的底层存储机制是完整存储不是分片存储这样吗，会有把文件拆分为多份，存储到不同的节点上吗？类似minio 的这种存储方式。

**Comment by sjqzhang** [comment]
不支持多磁盘路径配置，如果有这种需求，可以试一下软链接，go-fastdfs采用全对等设计，文件没有采取分片或分块设计，需要多少副本就用多少台机器组成集群，你多看看文档。

**Comment by zhangleijie** [comment]
好的 谢谢
