### ISSUE TITLE
双机文件同步失败和开启Google验证后无需code即可下载问题

### ISSUE THREAD

**Issue by zheast** [sjqzhang/go-fastdfs#195]
问题表述：如题所示
测试验证过程：
关键点在于support_group_manage 开关和group配置
1.当support_group_manage =false 和group不为空时，双机同步时会带上group值，即support_group_manage =false此时没生效，导致同步时获取文件url带上group，造成同步失败，
当设置support_group_manage =false 和group=“”后，同步成功

2.当设置support_group_manage =false 和group=“”时，启用 "enable_google_auth": true，下载文件无需google code， 查看源码（如下）,可知需gourp值参与验证:
		fullpath = r.RequestURI[len(Config().Group)+2 : len(r.RequestURI)]
		fullpath = strings.Split(fullpath, "?")[0] // just path
		scene = strings.Split(fullpath, "/")[0]
重新设置support_group_manage =true 和group=“group1”进行验证，验证功能正常，无code请求下载401被拒绝

**Comment by sjqzhang** [comment]
请用v1.3.9进行验证
