### ISSUE TITLE
开源协议的问题

### ISSUE THREAD

**Issue by shiersong** [sjqzhang/go-fastdfs#196]
您好，
我看了Lisence
这个软件的开源协议是使用类似于Apache的开源协议吧？
不是像C版的fastdfs所使用的GPL协议吧？

**Comment by sjqzhang** [comment]
商业闭源需商业授权

**Comment by shiersong** [comment]
其实我说的是你们这一个社区版的go-fastdfs，我知道你们还有一个商业版go-fastdfs。
我看到你们这个社区版的go-fastdfs的lisence中写到：

This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <https://unlicense.org>

那基于你们这个社区版的go-fastdfs进行商业闭源还需要商业授权吗？
