### ISSUE TITLE
iphone6拍摄的图片，jpeg缩放后旋转了

### ISSUE THREAD

**Issue by gonglb** [sjqzhang/go-fastdfs#198]
原图：
[321590053212_.pic_hd.jpg.zip](https://github.com/sjqzhang/go-fastdfs/files/4661645/321590053212_.pic_hd.jpg.zip)

缩放后的：
<img width="648" alt="WeChat96aca3dba43a629c12128f9d8efc7d27" src="https://user-images.githubusercontent.com/39292759/82545074-af78ab80-9b88-11ea-94c0-b94b41e51bd0.png">

对了，我是使用的docker搭建的

**Comment by sjqzhang** [comment]
第三方压缩库问题，建议自行压缩再上传。

**Comment by gonglb** [comment]
看框架这边能否解决，毕竟算是一个软件的bug，自行去压缩的话那这个框架的压缩功能意义就没多大了，之前就是看中张大牛的无缝衔接fastdfs和压缩功能，才使用的
