### ISSUE TITLE
文件自动去重的依据是什么？

### ISSUE THREAD

**Issue by chengyuansen** [sjqzhang/go-fastdfs#2]
试了下，同一个文件能够自动去重并返回已经上传的文件信息。想问下，文件去重的依据是什么？仅仅根据MD5吗？

**Comment by sjqzhang** [comment]
是的，根据md5自动去重

**Comment by chengyuansen** [comment]
如果仅仅根据MD5做去重的话，碰撞几率还是挺高的。建议除MD5外，加上文件类型，文件的字节长度共三个维度来做去重，这样碰撞概率会大大降低。

**Comment by sjqzhang** [comment]
会有，但概率极低，我暂时还没遇到过这种问题，你可以发两个文件内容不一样，MD5一样的文件给我么？

**Comment by chengyuansen** [comment]
这里好像没办法上传文件。下面这个链接的最下方有【快速 MD5 碰撞生成器】，使用方法在文章的最上方。我试过了，的确能够生成2个文件内容不同但MD5相同的文件。而且文件大小，文件类型都一样。遇到这种情况即便加上文件类型，文件的字节长度也解决不了碰撞问题。
https://blog.csdn.net/sysprogram/article/details/73753354

**Comment by sjqzhang** [comment]
已加入sha1算法去和，请帮忙验证一下
