### ISSUE TITLE
文件去重可能出现问题？

### ISSUE THREAD

**Issue by jianbiaoxu** [sjqzhang/go-fastdfs#20]
测试时候发现不是必然发生，但是概率不低。
就是多次上传相同文件，按照去重，应该返回的都是第一次上传的文件信息，但是有时候却返回的是无法打开文件失败，路径指向的是最新的地址。
open files/video/20190226/18/08/8/test.mp4: no such file or directory

使用的是sha1去重，搭建两台服务器，使用nginx做负载均衡。

**Comment by sjqzhang** [comment]
你看看两台服务器的相应目录有没有对应的文件？如果还有疑问加入群，大看看大伙有没有让到同样的问题？

**Comment by jianbiaoxu** [comment]
没有响应的目录，我看那些能够成功的是，有相应的目录，但是目录是空的，应该是想上传到指定目录，然后判断重复，返回旧的文件信息，把刚上传的删掉，然后就只剩下空目录了。

**Comment by sjqzhang** [comment]
你分析的非常正确，上传逻辑是这样的。

**Comment by jianbiaoxu** [comment]
用的是1.1.8版本，不好意思，忘记回复了。
