### ISSUE TITLE
文件莫名的消失

### ISSUE THREAD

**Issue by sleechengn** [sjqzhang/go-fastdfs#200]
上传了，过了一段时间后，就访问不到，也没有删除。

**Comment by sjqzhang** [comment]
从设计上看不应该存在这样的问题，群内也没收到这样的反馈，可以看看是不是被调用了删除api，或者使用不当造成。

**Comment by OTLCLoud** [comment]
我也出现了这种问题，没有调用过删除api，也没感觉哪里出错了
