### ISSUE TITLE
文件上传成功，删除报错leveldb not found

### ISSUE THREAD

**Issue by kfwang90** [sjqzhang/go-fastdfs#202]
文件上传成功，下载也是正常的。但删除报错，fileserver日志为：leveldb not found。有什么排查思路吗？

**Comment by sjqzhang** [comment]
可能是api参数错误，请参阅api文档或视频。

**Comment by kfwang90** [comment]
找到问题了，是上传的路径里面多一个路径符，比如/file//dir1/dir2 中间不能出现//这样。导致的这个问题。
