### ISSUE TITLE
我上传时中文文件名有空格，下载地址，下载出错

### ISSUE THREAD

**Issue by sleechengn** [sjqzhang/go-fastdfs#203]
我上传时中文文件名有空格，下载地址，下载出错

**Comment by Dongzai1005** [comment]
url编码

**Comment by sleechengn** [comment]
我是用http client，构造的url如果用urlencode编码，前面那个http://这些也会编码，难道，我要判断？每个路径中，有非ascii字符或空格或是非url字符，再进行url编码？

**Comment by Dongzai1005** [comment]
文件名编码就行，其他地址也不需要编码

**Comment by sjqzhang** [comment]
有空格中文等特殊字符需进行url编码。
