### ISSUE TITLE
从其它快速导入，一会儿出现错误

### ISSUE THREAD

**Issue by sleechengn** [sjqzhang/go-fastdfs#204]
open files/_tmp/20200525/be86ceb3-b4db-2ace-56d1-83829890d453: too many open files

**Comment by sleechengn** [comment]
已经调整了操作系统的最大打开数

**Comment by sjqzhang** [comment]
是最新版本么？请用最新版本测试看看。

**Comment by sjqzhang** [comment]
可能在之前的版本中存在不关闭文件描述符的bug
