### ISSUE TITLE
单一节点是否支持本地多硬盘？

### ISSUE THREAD

**Issue by LowEntropyBody** [sjqzhang/go-fastdfs#209]
我想到了一个办法，就是上传文件的时候指定path路径，然后把不同的硬盘挂到不同的path下。但这样的话就就得指定，对于外部的调用者来说他没法知道具体每个盘剩多少，也就不能知道应该存文件到哪个盘

**Comment by sjqzhang** [comment]
暂不支持，可以试试软链接或做lvm管理。
