### ISSUE TITLE
关于自定义AUTH_URL

### ISSUE THREAD

**Issue by wangran35** [sjqzhang/go-fastdfs#213]
我自定义的AUTH_URL想做自定义的业务逻辑，包括用户注册分配auth_token匹配，业务数据库存储，现在想获取leveldb中的KEY和value匹配到业务数据库中，AUTH_URL可以获取POST过来的FILE_MD5也就是文件数据库leveldb中的key吗？

**Comment by sjqzhang** [comment]
请不要关注leveldb的数据结构，保证业务隔离互不影响，不保证以后不会改leveldb的结构，自己就挖坑了。

**Comment by wangran35** [comment]
感谢你在百忙之中回复我，我想请教你一个问题，就是图片多服务器同写的业务模式是？主服务器先写，然后循环给每个服务器请求8080端口POST数据过去么？集群是要求在局域网还是只要IP都可以？
例如一台阿里云服务器和一台腾讯云服务器？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"小张"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 晚上6:22
收件人:&nbsp;"sjqzhang/go-fastdfs"<go-fastdfs@noreply.github.com&gt;;
抄送:&nbsp;"123456"<707229207@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sjqzhang/go-fastdfs] 关于自定义AUTH_URL (#213)





 
请不要关注leveldb的数据结构，保证业务隔离互不影响，不保证以后不会改leveldb的结构，自己就挖坑了。
