### ISSUE TITLE
案例收集

### ISSUE THREAD

**Issue by sjqzhang** [sjqzhang/go-fastdfs#214]
如果您在使用 go-fastdfs，欢迎将使用案例补充到这里，然后添加我们小助手的[微信](https://github.com/sjqzhang/go-fastdfs/blob/master/doc/wechat.jpg)，小助手会邀请各位进入go-fastdfs交流微信群。

例子

```
- xx公司
- www.example.com
- 空间容量：100T+ 文件数 10亿+
```

**Comment by tumq** [comment]
- 中通服创立信息科技有限公司
- www.ccsenrising.com
- 空间容量：2T+ 文件数 5000万+

**Comment by 522338473** [comment]
文件上传报错：
open /daa/files/_tmp/20200930/```````````: no such files or directory

**Comment by ahyin2019** [comment]
文件统计能否传日期参数？

**Comment by netyuchangfa** [comment]
重庆特迪科技有限公司
智慧之家物联网云平台
www.123667.com
[](http://www.123667.com)图片服务器：重庆IDC机房9台，青岛IDC机房7台，其它机房正在部署
空间容量：200T+ 文件数 3亿+

刚从阿里云迁移下来时遇到些麻烦，后来经过社区帮助逐步解决和稳定下来，现运行稳定，性能优异，维护简单方便！
感谢社区力量！
感谢所有贡献者！

**Comment by liutao841204** [comment]
- 北京星网锐捷网络技术有限公司
- https://www.ruijie.com.cn/
- 空间容量：2T+ 文件数 100W+
