### ISSUE TITLE
同名文件问题

### ISSUE THREAD

**Issue by CTFer** [sjqzhang/go-fastdfs#215]
同路径同名文件服务器返回的是第一次上传的文件路径，后续上传同名文件到服务器，服务器会自动重命名，但返回的路径仍然是原文件名。如首次上传 1.jpg，第二次上传 1.jpg 会被改名为 0_1.jpg,但返回的路径是1.jpg

**Comment by sjqzhang** [comment]
与设定规则有关，并非bu g
