### ISSUE TITLE
发现集群模式下，进程经常挂掉

### ISSUE THREAD

**Issue by tumq** [sjqzhang/go-fastdfs#218]
目前我们已经将本产品用于生产环境，并使用的集群模式，但是发现集群模式下，进程经常挂掉，而且没有任何挂掉的异常日志，就像进程凭空消失了一样

**Comment by sjqzhang** [comment]
没放后台运行，看教程。

**Comment by tumq** [comment]
是后台运行的，生产环境怎么可能不放后台运行呢？一直是后台运行的
