### ISSUE TITLE
文件删除问题

### ISSUE THREAD

**Issue by theJinFei** [sjqzhang/go-fastdfs#221]
您好！文件删除遇到点问题，希望得到您的解答。
- 目前上传文件会返回文件md5，删除文件时，根据md5进行删除
- 如果是多用户的场景，上传同一个文件（拿到的md5都相同），其中一个用户想删除，这样的话，会影响整个拥有这个文件的用户，请问，这种怎么解决？（感觉这种场景md5做唯一id，是不是有点问题？
- 我把文件去重给关了，这样的话，相同文件，不同时刻（应该是间隔分钟）提交相同文件，产生的md5都是不同的。
- 但是还有一个问题，没有间隔一分钟，相同文件，也会产生相同md5的问题。这样删除还会出现问题。请问这种情况该怎么解决？
- 上面测试都是使用postman直接发http中post请求
- **其结果是，关闭了文件去重功能，连续发多个请求（间隔少于1分钟），也会产生相同的md5，这样并不能标识文件的唯一性，多用户删除的时候，会出现问题**
- 下方是不同时刻间隔（多于一分钟），产生的文件md5.可以看到，都是不相同的。
![image](https://user-images.githubusercontent.com/34594300/87561658-8f301d80-c6ef-11ea-83a3-4bec7677f50e.png)
![image](https://user-images.githubusercontent.com/34594300/87561667-92c3a480-c6ef-11ea-80ee-f5640c926f05.png)
![image](https://user-images.githubusercontent.com/34594300/87561673-9525fe80-c6ef-11ea-9f17-72e45de7e287.png)

**Comment by sjqzhang** [comment]
文件删除在开启去重的情况下，全局唯一，删除相互影的(在定制版本中支持场景隔离功能，即场景唯一),禁用去重情况下，依赖路径年成md5,建议开启自动生成文件名，这样md5就全不一定。
