### ISSUE TITLE
delete接口401Unauthorized

### ISSUE THREAD

**Issue by waylon-gmail** [sjqzhang/go-fastdfs#226]
delete接口401Unauthorized
其它接口都正常，不明白这是为什么

**Comment by waylon-gmail** [comment]
因为开启了： "auth_url": “xxxxxxxxxx”。
目前还没找到怎么传token, 按照上传下载的方式传token识别不到

**Comment by waylon-gmail** [comment]
delete作为安全接口，只有指定ip能调用，不知道为什么还要校验token。auth_token不知道怎么传才行。求大佬指点。

**Comment by sjqzhang** [comment]
看文档或视频教程。

**Comment by waylon-gmail** [comment]
![image](https://user-images.githubusercontent.com/51048705/89097863-6a3ce980-d415-11ea-9957-c8e81601d2e0.png)
千万不能多传参数。有坑。
