### ISSUE TITLE
允许后缀名": "允许可以上传的文件后缀名，如jpg,jpeg,png等。有问题

### ISSUE THREAD

**Issue by Team-boy** [sjqzhang/go-fastdfs#227]
配置如下
 "绑定端号": "端口",
        "addr": ":8080",
        "是否开启https": "默认不开启，如需启开启，请在conf目录中增加证书文件 server.crt 私钥 文件 server.key",
        "enable_https": false,
        "PeerID": "集群内唯一,请使用0-9的单字符，默认自动生成",
        "peer_id": "4",
        "本主机地址": "本机http地址,默认自动生成(注意端口必须与addr中的端口一致），必段为内网，自动生成不为内网请自行修改，下同",
        "host": "http://192.168.40.8:8080",
        "集群": "集群列表,注意为了高可用，IP必须不能是同一个,同一不会自动备份，且不能为127.0.0.1,且必须为内网IP，默认自动生成",
        "peers": ["http://192.168.40.8:8080","http://192.168.40.7:8080","http://192.168.40.9:8080"],
        "组号": "用于区别不同的集群(上传或下载)与support_group_manage配合使用,带在下载路径中",
        "group": "group1",
        "是否支持按组（集群）管理,主要用途是Nginx支持多集群": "默认支持,不支持时路径为http://10.1.5.4:8080/action,支持时为http://10.1.5.4:8080/group(配置中的group参
数)/action,action为动作名，如status,delete,sync等",
        "support_group_manage": true,
        "是否合并小文件": "默认不合并,合并可以解决inode不够用的情况（当前对于小于1M文件）进行合并",
        "enable_merge_small_file": true,
    "允许后缀名": "允许可以上传的文件后缀名，如jpg,jpeg,png等。留空允许所有。",
        "extensions": ["jpeg","png"],
        "重试同步失败文件的时间": "单位秒",
        "refresh_interval": 1800,
        "是否自动重命名": "默认不自动重命名,使用原文件名",
        "rename_file": false,
        "是否支持web上传,方便调试": "默认支持web上传",
        "enable_web_upload": true,
        "是否支持非日期路径": "默认支持非日期路径,也即支持自定义路径,需要上传文件时指定path",
        "enable_custom_path": true,
        "下载域名": "用于外网下载文件的域名,不包含http://",
        "download_domain": "",
        "场景列表": "当设定后，用户指的场景必项在列表中，默认不做限制(注意：如果想开启场景认功能，格式如下：'场景名:googleauth_secret' 如 default:N7IET373HB2C5M6D ",
        "scenes": [],
        "默认场景": "默认default",
        "default_scene": "default",

报错

{'data': None, 'message': '(error)file extension mismatch', 'status': 'fail'}
{'data': None, 'message': '(error)file extension mismatch', 'status': 'fail'}
{'data': None, 'message': '(error)file extension mismatch', 'status': 'fail'}
{'data': None, 'message': '(error)file extension mismatch', 'status': 'fail'}
{'data': None, 'message': '(error)file extension mismatch', 'status': 'fail'}
{'data': None, 'message': '(error)file extension mismatch', 'status': 'fail'}
{'data': None, 'message': '(error)file extension mismatch', 'status': 'fail'}
{'data': None, 'message': '(error)file extension mismatch', 'status': 'fail'}
{'data': None, 'message': '(error)file extension mismatch', 'status': 'fail'}
{'data': None, 'message': '(error)file extension mismatch', 'status': 'fail'}

**Comment by sjqzhang** [comment]
增加点 修如： .png .gif 等。

**Comment by ljyf5593** [comment]
后缀检测应该不区分大小写
