### ISSUE TITLE
微信小程序下载doc、docx文件，content-type错误导致文件后缀为.zip

### ISSUE THREAD

**Issue by GanHuaLin** [sjqzhang/go-fastdfs#233]
#127 
请问下改怎么解决这个问题，我也遇到了！
微信小程序里下载doc、docx文件，后缀是.zip

**Comment by sjqzhang** [comment]
这个可能与客户端对http头处理有关

**Comment by sjqzhang** [comment]
在新版本中，支持自定义下载文件名，在下载的url后面加上  ?name=你的文件名.后缀&download=1

**Comment by GanHuaLin** [comment]
> 在新版本中，支持自定义下载文件名，在下载的url后面加上 ?name=你的文件名.后缀&download=1

请问下，自定义下载文件名，最新版的docker镜像里支持了吗？
