### ISSUE TITLE
集群数据同步超时

### ISSUE THREAD

**Issue by benbochong** [sjqzhang/go-fastdfs#234]
[main.(*Server).postFileToPeer] Post http://[ip1]::8080/syncfile_info read tcp [ip2]:49580->[ip1]:8080: i/o timeout

**Comment by benbochong** [comment]
要死了，更新最新版本，数据全都给同步成1k了。成了删库罪人

**Comment by cdoer** [comment]
> 
> 
> 要死了，更新最新版本，数据全都给同步成1k了。成了删库罪人

兄弟  你还好没有

**Comment by sjqzhang** [comment]
应该是配置导致网络有问题，排查配置问题，如果是线上问题可以加群反馈协助解决。
