### ISSUE TITLE
上传相同文件的时候，返回结果没错，但是存储目录下把第二个相同文件给存下来了，只是没有重命名

### ISSUE THREAD

**Issue by fjsleeping** [sjqzhang/go-fastdfs#239]
![image](https://user-images.githubusercontent.com/33787282/98926680-9555cf80-2512-11eb-99d7-9d82c5930dc0.png)
上传相同文件的时候，返回结果没错，但是存储目录下把第二个相同文件给存下来了，只是没有重命名

**Comment by fjsleeping** [comment]
没人回答，我自己改了
![image](https://user-images.githubusercontent.com/33787282/99163156-d252d980-273f-11eb-973e-dac7f94affbb.png)

**Comment by fjsleeping** [comment]
没人回答，我自己改了
![image](https://user-images.githubusercontent.com/33787282/99163156-d252d980-273f-11eb-973e-dac7f94affbb.png)

**Comment by sjqzhang** [comment]
你的意思是临时文件没有删除对么？

**Comment by fjsleeping** [comment]
> 你的意思是临时文件没有删除对么？

是的，我提交了“Pull requests‘你看看

**Comment by sjqzhang** [comment]
用户允许重复的情况下才保留，加群讨论。

**Comment by fjsleeping** [comment]
默认去重：true的情况下还是保留，而且并没生成正式的文件命名，是生成一个缓存文件名
