### ISSUE TITLE
权限管理问题

### ISSUE THREAD

**Issue by xvzhonglin** [sjqzhang/go-fastdfs#24]
您好,我在使用中感觉软件很不错,但是权限控制这个让我有点迷糊,白名单127.0.0.1,按理说除开集群本身的ip和这个127.0.0.1可以管理外其他的机器不可以管理啊,但是我用另外的机器可以上传可以删除,请问这个问题是必须要配合防火墙或nginx等三方软件,还是我设置有误?应该是软件没做这个限制吧,我在其他ip查看stat提示没权限.

**Comment by sjqzhang** [comment]
我还不是特别明白你的意思，微信上聊。
