### ISSUE TITLE
是否支持类似FastDFS的allow_hosts参数

### ISSUE THREAD

**Issue by linshan8727** [sjqzhang/go-fastdfs#242]
是否支持类似FastDFS的allow_hosts参数
![image](https://user-images.githubusercontent.com/66673229/98933718-fe8e1080-251b-11eb-9eb5-f683f6b516fd.png)

**Comment by sjqzhang** [comment]
对内参考配置中有admin_ips ，对外的只支持自定义授权，具体看文档或视频 。
