### ISSUE TITLE
是否可以考虑支持创建文件副本

### ISSUE THREAD

**Issue by JornTang** [sjqzhang/go-fastdfs#249]
是否可以考虑支持创建文件副本

**Comment by sjqzhang** [comment]
什么场景要用副本？重新上传文件不能满足？

**Comment by JornTang** [comment]
因为我们的管理的电子文件是支持在线编辑的，而有些文件是不可以编辑源文件。所以在编辑前我们会创建一个副本让客户进行编辑。

**Comment by sjqzhang** [comment]
那就重新上传编辑后的内容就OK ，这个是基本的文件系统，不会支持过多的业务方面的需求。
