### ISSUE TITLE
同一个文件第二次上传问题

### ISSUE THREAD

**Issue by gaoxjin** [sjqzhang/go-fastdfs#25]
同一个文件第二次上传指定另外的目录，实际是没有上传，直接返回第一次上传文件的信息
1.但是另外的目录是创建了，既然不上传到这个目录为什么要创建目录？
2.判断为重复文件直接返回第一次上传文件的信息，这里设计的有点简单粗暴。

**Comment by sjqzhang** [comment]
创造不删是出于性能考虑，重复文化不返回上一次的文件信息，应该怎么返回？想听听你的意见

**Comment by rexlibing** [comment]
第二次上传同样文件做个软连接过去到新目录呗~
