### ISSUE TITLE
使用大文件上传时同一集群内的机器无法同步

### ISSUE THREAD

**Issue by lltony** [sjqzhang/go-fastdfs#255]
我在同一组内部署了两台机器，192.168.16.60,192.168.16.62，当我使用/big/upload的方式上传文件到192.168.16.60之后使用返回的地址去访问192.168.16.62，显示leveldb: not found。
![image](https://user-images.githubusercontent.com/79556375/108942249-9b228b80-7691-11eb-9c2d-60efed4f9d7f.png)
![image](https://user-images.githubusercontent.com/79556375/108942273-a970a780-7691-11eb-87bd-67090a77f6ea.png)

**Comment by sjqzhang** [comment]
大文件上传需要多一个步骤，进行URL置换：
例如上传后的大文件路径为： http://10.9.22.120:8081/group1/big/upload/77fafa5fc868bce20cf236412d9d95e6
进行置换的API为：其中    77fafa5fc868bce20cf236412d9d95e6  为随机产生的置换因子，每次上传这个因子都会不一样。
http://10.9.22.120:8081/group1/get_file_info?md5=77fafa5fc868bce20cf236412d9d95e6
```json
{
  "message": "",
  "status": "ok",
  "data": {
    "name": "container_vs_vm.jpg",
    "rename": "container_vs_vm.jpg",
    "path": "files/default/20210225/16/24/1",
    "md5": "bacb060f58a73434d880f6c25036db2a",
    "size": 55405,
    "peers": [
      "http://10.9.22.120:8081"
    ],
    "scene": "",
    "timeStamp": 1614241450,
    "offset": -1
  }
}
```
用path+rename就是要访问的路径了。
