### ISSUE TITLE
目前不支持跨域？

### ISSUE THREAD

**Issue by jacobzeng** [sjqzhang/go-fastdfs#26]
谢谢提供这个工具
我在用javascript上传的时候，浏览器发送OPTIONS请求的时候，因为没有反馈跨域相关的Response Headers，被拒绝了，这个能支持吗？

**Comment by sjqzhang** [comment]
可以提供支持，你有相关资料的链接或直接提供示例么？

**Comment by jacobzeng** [comment]
意思就是当HTTP Method是OPTIONS的时候，Http Response Header里面要有
Access-Control-Allow-Origin: *，这时候不需要处理任何body，只需要设置Http Response Header就行

参考请求如下
Request URL: http://192.168.3.23:33310/upload
Request Method: OPTIONS

如果是Java Spring Web为参考的话，一般会设置跨域或者是写一个web filter处理所有OPTIONS请求，并直接设置Http Response Header并返回
registry.addMapping("/**").allowedOrigins("*").allowedMethods("GET", "POST", "DELETE");

参考资料https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by jacobzeng** [comment]
现在浏览器会提示错误如下：

Access to XMLHttpRequest at 'http://192.168.3.23:33310/upload' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by sjqzhang** [comment]
可以加微信，我编译一个包给你试一下，看看可不可以

**Comment by jacobzeng** [comment]
好的，马上加你

**Comment by sjqzhang** [comment]
下一版本支持。

**Comment by kindomcat** [comment]
请问现在的版本支持跨域了吗
