### ISSUE TITLE
自定义验证结果一直为fail

### ISSUE THREAD

**Issue by SiGuaJ** [sjqzhang/go-fastdfs#260]
我参照例子提供了接口给go-fastdfs，获取到了auth_token也验证成功返回了“ok”字符串，但是上传和下载的接口依然是auth fail，请问验证url返回的ok字符串是还需要怎么封装吗？我用postman调取验证接口的结果："ok"，这样是否正确？

**Comment by sjqzhang** [comment]
不清楚你具体的使用，请使用文档自带的例子进行验证，再进行自改造。

**Comment by SiGuaJ** [comment]
通过运行例子的python解决，因为我使用的是asp,net框架，返回的是“ok”，需要返回不带引号的ok才能验证成功。
