### ISSUE TITLE
Unstable path

### ISSUE THREAD

**Issue by jabalnurlazim** [sjqzhang/go-fastdfs#261]
It came to my attention that I'm encountering an unstable file location or path where the file is being uploaded. 

For example:
I upload fileA to the path; test1. sometimes its being uploaded on the said path but there are time too that its being uploaded to the other existing path.

Please help. Thank you.

![Screen Shot 2021-03-21 at 5 00 56 PM](https://user-images.githubusercontent.com/22547128/111899472-bd78b080-8a67-11eb-9c1e-e00358a8342b.png)

![Screen Shot 2021-03-21 at 5 01 41 PM](https://user-images.githubusercontent.com/22547128/111899430-94582000-8a67-11eb-8a63-52882649214a.png)
![Screen Shot 2021-03-21 at 5 01 47 PM](https://user-images.githubusercontent.com/22547128/111899433-94f0b680-8a67-11eb-9fd0-f25d7432cb44.png)

**Comment by sjqzhang** [comment]
与开启是否去重有关，你可以允许重复试试
