### ISSUE TITLE
外网文件迁移到内网

### ISSUE THREAD

**Issue by hpzou** [sjqzhang/go-fastdfs#265]
您好，如何将外网的go-fastdfs上传的文件迁移到内网中去，然后只通过改ip的形式访问到文件

**Comment by hpzou** [comment]
改ip的意思是，我是通过domain+path去下载文件的，如果换了domain的IP地址，还能获取文件就行

**Comment by sjqzhang** [comment]
还是不明白你的意思，domain可以自定义，理论上迁移是没有问题的，自己多看文档多试试吧

**Comment by hpzou** [comment]
就是两个网络不互通的环境下，怎么去迁移文件，然后还能通过url去访问迁移后的文件
