### ISSUE TITLE
集群内文件无法同时删除

### ISSUE THREAD

**Issue by lovelygz** [sjqzhang/go-fastdfs#271]
1：nginx配置了group1 2台服务器：

upstream gofastdfs-group1 {
	server 172.16.18.190:16166;
	server 172.16.18.72:16166;
	ip_hash;     #notice:very important(注意)
    }
    #upstream gofastdfs-group2 {
        #server 10.1.51.70:8083;
	#server 10.1.14.36:8083;
	#ip_hash;     #notice:very important(注意)
    #}

    server {
	listen       88;
	server_name  172.16.18.190;

        if ( $request_uri ~ /godfs/group ) {
            # 注意group会随组的前缀改变而改变
            rewrite ^/godfs/(.*)$ /$1 last;
        }
	location ~ /group(\d) { 
	    #统一在url前增加godfs,以便统一出入口。
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
	    proxy_pass http://gofastdfs-group$1;
	}
	location ~ /godfs/delete { 
	    #这是一个横向扩展配置，前期可能只有一个集群group1,当group1满后，只需将上传指向group2,
	    #也就是将rewrite , proxy_pass 中的group1改为group2即可。
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
	    rewrite ^/godfs/delete /group1/delete break;
	    proxy_pass http://gofastdfs-group1;
	}
	location ~ /godfs/upload { 
	    #这是一个横向扩展配置，前期可能只有一个集群group1,当group1满后，只需将上传指向group2,
	    #也就是将rewrite , proxy_pass 中的group1改为group2即可。
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
	    rewrite ^/godfs/upload /group1/upload break;
	    proxy_pass http://gofastdfs-group1;
	}

2：调用API  /godfs/upload 上传了文件。在两台服务器都能看到相应的文件。
3：调用API  /godfs/delete 删除文件，但是只删除了server 172.16.18.72的，另一个server的没有删除。

请问这是bug，还是我的配置有错呢？
期待答复，谢谢～～

**Comment by sjqzhang** [comment]
查看日志，应该是配置问题，注意网络不能是nat模式

**Comment by lovelygz** [comment]
2021-04-30 11:37:34 [ERR] [fileserver.go:1009] [main.(*Server).CheckAuth] main.JsonResult.Status: ReadString: expects " or n, but found 4, error found in #10 byte of ...|"status":400,"error"|..., bigger context ...|mestamp":"2021-04-30T03:37:34.122+0000","status":400,"error":"Bad Request","message":"Required Strin|...

错误日志，能帮忙看一下吗？谢谢～～

**Comment by lovelygz** [comment]
2021-04-30 11:37:34 [ERR] [fileserver.go:1009] [main.(*Server).CheckAuth] main.JsonResult.Status: ReadString: expects " or n, but found 4, error found in #10 byte of ...|"status":400,"error"|..., bigger context ...|mestamp":"2021-04-30T03:37:34.122+0000","status":400,"error":"Bad Request","message":"Required Strin|...

错误日志，能帮忙看一下吗？谢谢～～
