### ISSUE TITLE
关于分块上传的问题。

### ISSUE THREAD

**Issue by bidw77** [sjqzhang/go-fastdfs#277]
Go-fastdfs太棒了，十分感谢！请问是否支持Tus的Concatenation扩展？

**Comment by sjqzhang** [comment]
这个需要你实测验证。

**Comment by bidw77** [comment]
![360截图18061214184075](https://user-images.githubusercontent.com/73728460/119352536-55299380-bc91-11eb-8cc3-fc1e2affb63a.png)
StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:\r\n{\r\n  Access-Control-Allow-Headers: Authorization, Content-Type, Depth, User-Agent, X-File-Size, X-Requested-With, X-Requested-By, If-Modified-Since, X-File-Name, X-File-Type, Cache-Control, Origin\r\n  Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE\r\n  Access-Control-Allow-Origin: *\r\n  Access-Control-Expose-Headers: Authorization\r\n  Tus-Resumable: 1.0.0\r\n  X-Content-Type-Options: nosniff\r\n  Date: Mon, 24 May 2021 13:01:18 GMT\r\n  Content-Length: 17\r\n  Content-Type: text/plain; charset=utf-8\r\n}

**Comment by 838239178** [comment]
> Go-fastdfs太棒了，十分感谢！请问是否支持Tus的Concatenation扩展？

老哥你知道官方文档用`uppy`tus协议上传时携带的`callback_url`是干嘛的呢
