### ISSUE TITLE
Tus的Concatenation扩展问题

### ISSUE THREAD

**Issue by bidw77** [sjqzhang/go-fastdfs#278]
![360截图18061214184075](https://user-images.githubusercontent.com/73728460/119352536-55299380-bc91-11eb-8cc3-fc1e2affb63a.png)
StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:\r\n{\r\n  Access-Control-Allow-Headers: Authorization, Content-Type, Depth, User-Agent, X-File-Size, X-Requested-With, X-Requested-By, If-Modified-Since, X-File-Name, X-File-Type, Cache-Control, Origin\r\n  Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE\r\n  Access-Control-Allow-Origin: *\r\n  Access-Control-Expose-Headers: Authorization\r\n  Tus-Resumable: 1.0.0\r\n  X-Content-Type-Options: nosniff\r\n  Date: Mon, 24 May 2021 13:01:18 GMT\r\n  Content-Length: 17\r\n  Content-Type: text/plain; charset=utf-8\r\n}

**Comment by sjqzhang** [comment]
fileserver支持tus协议使用的是tusd，支不支持Concatenation 要看https://github.com/tus/tusd  是否支持，使用早期的1.0版本。

**Comment by bidw77** [comment]
Tus解决了分块上传的问题，您是否可以考虑升级tusd版本来解决分块上传的问题。

**Comment by sjqzhang** [comment]
这个后面没有那么忙的时候做一下升级，现在忙手头上的工作。
