### ISSUE TITLE
几个问题？

### ISSUE THREAD

**Issue by zhbgs2000** [sjqzhang/go-fastdfs#28]
1、文件上传如何直接通过浏览器打开访问？
如上传图片文件成功后，响应地址http://localhost:8080/group1/image/logo_icon.png，直接通过google和360浏览器打开均弹出下载框了，是否需要做什么配置？

2、签权上传？
假设上传接口直接对外开放，是否支持类似nginx的push签权模式？要如何实现公网上传的签权？

3、断点续传？
能够提供java版断点续传的示例或实现机制？目前看到官网是go版的示例

**Comment by sjqzhang** [comment]
Nginx的push鉴权有资料吗？应用广泛么？
