### ISSUE TITLE
download_domain 前缀 https/http 问题

### ISSUE THREAD

**Issue by jiatiejun** [sjqzhang/go-fastdfs#281]
你好，服务器很好用，只是具体实施的时候，发现一点不方便的场景：

我们后台所有的服务，都是通过 nginx 反向代理的，所以, https 证书也是由 nginx 承载的，
这样就存在这种情况，利用 nginx 代理进来用的是 https 协议
但是内部反向代理没有启用 ssl 的 go-fastdfs 时，被认为是 http ，
这样在 download_domain 其前缀附加的是 http 但是和 nginx 外部的 https 不同
能否把 download_domain 的前缀带上，
让客户自己选择（虽然出错的概率更大了，但是更灵活了，比如这种场景，nginx 是 https 但是 proxy_pass 是 http）

再就是默认的无定制路径时，采用.Format("20060102/15/04") 作为默认路径
这个能否也允许定制层数，对于文件上传量比较小的场景，文件夹就太多了
可以定制模板，或者多几个选择（比如文件量小的场景，感觉用Format("2006/0102")只有年月日的路径，再配合 rename_file = true 就足够用了）

**Comment by sjqzhang** [comment]
路径可以使用自定义路径，返回最新版可以加https前辍
