### ISSUE TITLE
集群间同步问题反馈

### ISSUE THREAD

**Issue by r6c** [sjqzhang/go-fastdfs#282]
集群间文件同步是多线程进行，但好像没有断点续传功能，大文件同步过程中若是网络波动，会造成重新传输，即使已经传输了90%，也会被删除重传。使用版本 V1.4.2
![image](https://user-images.githubusercontent.com/45527749/121004769-a5404400-c7c1-11eb-8d25-bd4992565b82.png)

**Comment by sjqzhang** [comment]
集群间同步不使用断点续传，你们环境应该是跨地域的场景，需加大超时设置。
