### ISSUE TITLE
开启Google认证,非admin_ips下载也不需要认证？

### ISSUE THREAD

**Issue by wangyufengGoGoGo** [sjqzhang/go-fastdfs#283]
我在服务器部署了服务   自己电脑上查询访问出现Can only be called by the cluster ip or 127.0.0.1 or admin_ips(cfg.json),current ip:172.16.65.35正常的  上传时会需要认证   但下载时可以随意下载

下源码   
```
if Config().EnableGoogleAuth && !c.IsPeer(r) {
		fullpath = r.RequestURI[len(Config().Group)+2 : len(r.RequestURI)]
		fullpath = strings.Split(fullpath, "?")[0] // just path
		scene = strings.Split(fullpath, "/")[0]
		code = r.FormValue("code")
		if secret, ok = c.sceneMap.GetValue(scene); ok {
			if !c.VerifyGoogleCode(secret.(string), code, int64(Config().DownloadTokenExpire/30)) {
				return false, errors.New("invalid google code")
			}
		}
	}
```
`http://172.16.4.35:2587/group1/exe/application.yml` 下载的路径不存在sence    导致验证通过了

**Comment by wangyufengGoGoGo** [comment]
![image](https://user-images.githubusercontent.com/30011407/121478643-d441fa00-c9fb-11eb-8e21-b5c6a25a6e58.png)
这里貌似少了自定义path是谷歌验证的情况

**Comment by sjqzhang** [comment]
要在集群之前做访问，看文档或视频。
