### ISSUE TITLE
指定存储文件夹，上传相同名字的图片会被最开始的图片所覆盖

### ISSUE THREAD

**Issue by yyccQQu** [sjqzhang/go-fastdfs#284]
<img width="222" alt="屏幕快照 2021-06-09 下午9 52 35" src="https://user-images.githubusercontent.com/32674176/121405051-a1512500-c96d-11eb-8b2c-9a8f7c015fc0.png">

- 指定存储文件夹后->上传 icon_bank_check.png文件后 ->再次上传icon_bank_check.png文件
- 第二个icon_bank_check 文件名为 0_icon_bank_check.png，但是返回的结果是依然是icon_bank_check.png

返回的结果依然是
```
obj.Url: http://localhost:8080/group1/testimg/icon_bank_check.png?name=icon_bank_check.png&download=1
```

**Comment by DonaldY** [comment]
根据 md5 避免重传了吧

**Comment by betazk** [comment]
我只要指定了文件路径，哪怕不是同一个文件，只要指定的文件名相同，都无法覆盖

**Comment by qinxh** [comment]
enable_distinct_file设置 false 试试

**Comment by sjqzhang** [comment]
指定路径时支持覆盖，这是go-fastdfs的特性
