### ISSUE TITLE
配置文件cfg.json中的show_dir配置不明白

### ISSUE THREAD

**Issue by 83790885** [sjqzhang/go-fastdfs#285]
"是否显示目录": "默认显示,方便调试用,上线时请关闭",
"show_dir": true,

你好，上面是cfg.json配置文件中的一个配置，不知道设置true或false会影响哪里，两个值我都改过，但是没有发现哪里有变化？不知道这个参数具体是设置哪块的？

**Comment by sjqzhang** [comment]
显示文件目录，就像windows资源理管器那样。
