### ISSUE TITLE
大文件上传后，通过文件id无法找到文件信息了

### ISSUE THREAD

**Issue by bkzy-wangjp** [sjqzhang/go-fastdfs#286]
2021年6月10日拉取的master分支，win10系统下使用大文件上传功能，
按照[#255](https://github.com/sjqzhang/go-fastdfs/issues/255)中大文件上传后的URL置换方法找不到文件了。
例如：上传后的文件路径为 `http://192.168.2.31:8091/group1/big/upload/ce25f57078ee43af9f7ee0e22d2de283`, 在big文件夹下可以找到该文件，使用上述连接也可以下载文件，但无法使用API进行置换URL，计算出文件的MD5后使用秒传也失败。
使用API`http://192.168.2.31:8091/group1/get_file_info?md5=ce25f57078ee43af9f7ee0e22d2de283`得到的结果为：
```
{
  "data": null,
  "message": "leveldb: not found",
  "status": "fail"
}
```
![](https://img-blog.csdnimg.cn/20210611181828322.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80MTYyMTcwNg==,size_16,color_FFFFFF,t_70)
![在这里插入图片描述](https://img-blog.csdnimg.cn/20210611181859873.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80MTYyMTcwNg==,size_16,color_FFFFFF,t_70)

**Comment by sjqzhang** [comment]
可以使用已修复的代码试一下

**Comment by bkzy-wangjp** [comment]
已经可以了，谢谢。
![image](https://user-images.githubusercontent.com/42510334/122145301-958ec280-ce87-11eb-8da5-1916378fcd59.png)
