### ISSUE TITLE
下载文件是否支持重命名

### ISSUE THREAD

**Issue by kiritokun07** [sjqzhang/go-fastdfs#292]
请问下载文件时是否支持给文件自定义新的名称？

前后端分离，前端点击`http://ip:port/group/1.jpg?download=1`时下载的文件为1.jpg，因为不是同源所以a标签的download的属性无效，请问是否有什么请求参数可以给下载的文件重命名，不想通过后端走一遍文件流

**Comment by sjqzhang** [comment]
新版本应该支持。name参数还是filename忘记了。

**Comment by kiritokun07** [comment]
3q~是name=xx.jpg
