### ISSUE TITLE
为什么文件会丢失

### ISSUE THREAD

**Issue by OTLCLoud** [sjqzhang/go-fastdfs#293]
我上传的照片，偶尔会出现在对应路径下找不到这个照片的情况；比如：我之前上传了一个数据集，其中有1264张照片，但是现在统计了一下，只有1122张了，但是调用那个文件统计信息API，显示的图片数量是正确的，为什么会出现这种情况啊！小白不太懂，烦请各位大佬能说清楚一些，感激不尽

**Comment by sjqzhang** [comment]
看看有没有开启去重功能，你可以关闭去重功能试一试，应该不存在你说的这种情况。

**Comment by OTLCLoud** [comment]
去重功能一直关着呢

**Comment by OTLCLoud** [comment]
今天又试了试，我甚至重新部署了一遍，去重功能也关了，早上
在files/0709/chaxiao8ml/870路径下上传了870张照片，
在files/0709/chaxiaoml/844路径下上传了844张照片，
在files/0709/test路径下上传了1张照片，调用statAPI统计fileCount一共1715张，一切都很正常，
但是下午一看，870张照片变成了824张，844张照片变成了808张，更离谱的是调用statAPI统计fileCount变成了1721张，不少反多？这些数据都是刚测出来，搞不懂为什么
