### ISSUE TITLE
文件上传问题

### ISSUE THREAD

**Issue by lmiao2017** [sjqzhang/go-fastdfs#294]
您好，想请问下，我直接往files目录下面拷贝或者删除文件(针对所有节点操作)，跟用接口上传和删除有区别吗？我们这边的场景有大量小文件需要上传。通过接口单个文件上传耗时特别久，所以想通过直接拷贝的方式来实现，而且经过测试也能够请求到，所以想请教下这种方式有什么弊端？

**Comment by sjqzhang** [comment]
这种方式不推荐，因为会导致文件与元数据不一致，如果后面你想用到元数据就基本不太可能，因为元数据已经不准确。

**Comment by lmiao2017** [comment]
好的  谢谢
