### ISSUE TITLE
还是文件丢失问题

### ISSUE THREAD

**Issue by OTLCLoud** [sjqzhang/go-fastdfs#295]
今天又试了试，我甚至重新部署了一遍，去重功能也关了，早上
在files/0709/chaxiao8ml/870路径下上传了870张照片，
在files/0709/chaxiaoml/844路径下上传了844张照片，
在files/0709/test路径下上传了1张照片，调用statAPI统计fileCount一共1715张，一切都很正常，
但是下午一看，870张照片变成了824张，844张照片变成了808张，更离谱的是调用statAPI统计fileCount变成了1721张，不少反多？这些数据都是刚测出来，搞不懂为什么[https://github.com/sjqzhang/go-fastdfs/issues/293](url)

**Comment by sjqzhang** [comment]
看下日志有没有删除的记录

**Comment by OTLCLoud** [comment]
没看到有删除的记录，我现在怀疑是服务器的问题，因为集群有两个组，group1就总是出现这个丢文件的问题，group2就很正常，但是又不知道为什么调用statAPI统计的照片数量会多

**Comment by sjqzhang** [comment]
统计API可能存在一定的数据偏差，因为读的本地数据，如果集群出现不同步问题，数据可能存在一定的偏差，但不影响使用。
