### ISSUE TITLE
文件路径携带小数点后，无法找到文件夹

### ISSUE THREAD

**Issue by vlinxh** [sjqzhang/go-fastdfs#297]
![image](https://user-images.githubusercontent.com/9361471/125925379-63d3cee3-bdaa-43ac-8740-ce92a72f894e.png)
![image](https://user-images.githubusercontent.com/9361471/125925475-36604cbb-45a2-46f4-ae58-07839a957e0d.png)

**Comment by sjqzhang** [comment]
为了安全替换掉了，这个不做修复，请不要带点。
