### ISSUE TITLE
双机文件没有自动同步

### ISSUE THREAD

**Issue by chengyuansen** [sjqzhang/go-fastdfs#3]
双机配置文件相同："peers": ["http://192.168.1.199:8080","172.16.70.123:7080"],	"group": "group1",
一台centos7.4，172.16.70.123:7080。一台win10，http://192.168.1.199:8080。先单独启动172.16.70.123:7080（此时peers节点没有配置http://192.168.1.199:8080），上传2个文件。查看状态结果如下：[{"date":"20190117","totalSize":8944,"fileCount":2},{"date":"all","totalSize":8944,"fileCount":2}]。
把win10节点配置好并启动fileserver，把centos节点纳入集群，并重新启动2台server。发现win10上并没有自动把centos上已上传的2个文件同步过来。状态：[{"date":"all","totalSize":0,"fileCount":0}]

**Comment by sjqzhang** [comment]
你的配置错误了，少了http://   应该是http://172.16.70.123:7080

**Comment by chengyuansen** [comment]
我马大哈了。
建议加个配置文件的检查，毕竟像我这样的马大哈也不少。因为启动的时候没有任何错误，还以为配置都是OK的。
另外，感觉您这个文件服务器真心不错，但现阶段缺少文档。比如像您说的后来加入的服务器需要手动同步等说明，您不说我们也不知道。还有感觉group是不是同步组？同一个group才会同步，不是同一个group不会同步？

**Comment by sjqzhang** [comment]
好的，后面加入自检功能
