### ISSUE TITLE
楼主能编译一个 arm的版本吗

### ISSUE THREAD

**Issue by carry1991** [sjqzhang/go-fastdfs#307]
arm 内核不能使用

**Comment by sjqzhang** [comment]
可以参照Dockerfile中的配置进行设置，调整增加GOARCH=arm即可进行编译，如下：

RUN set -xe; \
	apk update; \
	apk add --no-cache --virtual .build-deps \
	git; \
	mkdir -p /root/repo ; cd /root/repo ; \
	git clone https://github.com/sjqzhang/go-fastdfs ; \
	cd go-fastdfs; mv vendor src ; mv src .. ; cd .. ; mv go-fastdfs src/github.com/sjqzhang/ ; export GOPATH=/root/repo ; cd  src/github.com/sjqzhang/go-fastdfs ; \
	 export GO111MODULE="off"; \
	CGO_ENABLED=0 GOARCH=arm go build -a -installsuffix cgo -o fileserver; \
	ls -lh .;
