### ISSUE TITLE
上传后。md5值计算错误

### ISSUE THREAD

**Issue by reancool** [sjqzhang/go-fastdfs#308]
偶尔上传成功后 md5 计算错误

服务端配置关闭了去重，但是可以确定，这个文件是没有上传过的，文件名称也是没有过的。

![微信截图_20210910115738](https://user-images.githubusercontent.com/15047522/132797690-b2f643d6-0867-40bf-b2b6-bf7cc552fc13.png)

有老铁遇到同样问题的话，记得要用自己计算的 md5，上传接口返回的md5有几率错误，

**Comment by sjqzhang** [comment]
优先排查应用端
