### ISSUE TITLE
无法跨域上传

### ISSUE THREAD

**Issue by 17661152** [sjqzhang/go-fastdfs#31]
![image](https://user-images.githubusercontent.com/49092294/55274339-4b56b080-5312-11e9-9efa-89618a7f0dae.png)

**Comment by sjqzhang** [comment]
请用最新版本，重新生成配置，确认开启跨域支撑！

**Comment by 17661152** [comment]
还是无法跨越上传，下载的是最新版本了。v1.2.6   错误信息：X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.  应该是ajax请求响应的json无法跨域
