### ISSUE TITLE
Can you dynamically add nodes?

### ISSUE THREAD

**Issue by lonnietc** [sjqzhang/go-fastdfs#315]
Hello,

I am looking for a good alternative to IPFS in Golang for a P2P project that would need to support many thousands of Peers and I am wondering how easily go-fastdfs scales if nodes are dynamically added and removed as in a P2P operation.

Also, it is possible to "pin" files to a specific node and still be accessible to those files from other nodes?

Any help would be greatly appreciated.
Thanks in advance

**Comment by lonnietc** [comment]
Regarding the file pinning, what I need is to be able to upload files to specific "fileserver" nodes but still be able to read those files from other nodes in the massive cluster.

Can you please discuss this and if it is possible since I would assume that this could be part of the "upload" API call.

curl -F file=@http-index-fs http://10.1.xx.60:8080/group1/upload

turns out that your "group1" also does not work in the examples that I tired.

Thanks in advance.

**Comment by sjqzhang** [comment]
https://sjqzhang.github.io/go-fastdfs/authentication.html#custom

https://sjqzhang.github.io/go-fastdfs/#advantage

https://sjqzhang.github.io/go-fastdfs/install.html#compiler_install

**Comment by lonnietc** [comment]
Thank you, but this does not really tell me anything about how to upload a file to a particular node.

I actually read all of this documentation recently as well which is why I still have the questions.

Can you give me a curl example?

**Comment by lonnietc** [comment]
On dynamically adding nodes the closest that you have in documentation is:

https://sjqzhang.github.io/go-fastdfs/install.html#small-cluster

but this seems to require me to manually add each node to the configuration and I need the nodes to auto-discover other nodes without having to add them by hand.
