### ISSUE TITLE
Pinning documents to particular nodes?

### ISSUE THREAD

**Issue by lonnietc** [sjqzhang/go-fastdfs#317]
Hello,

I thought that I had asked this, but did not see any post or reply.

Is it possible to upload a file (document, etc.) to a particular node so that it resides on that node when others need it?

If so, then can you please give me an example as most of the documentation that I have read is in Chinese and I do not understand?

thanks

**Comment by sjqzhang** [comment]
Go-fastdfs is designed with small clusters forming large clusters. Data in a small cluster is equal, while data in a large cluster is unequal. Of course, you can add a proxy layer to achieve transparent access, but this will introduce a single point of problem. Therefore, you are advised not to use this method. As for the documentation, use Google Translate to read it.

**Comment by lonnietc** [comment]
Hello,

This is really a type of feature that IPFS has and could come in handy if it were built into your filesystem, but I have not seen it in many other systems as well.
