### ISSUE TITLE
Can nodes dynamically add to the cluster?

### ISSUE THREAD

**Issue by lonnietc** [sjqzhang/go-fastdfs#318]
Hello,

I am reading your documentation now.

Can new nodes dynamically join the cluster, or do they have to be added to the configuration file first and then restart the cluster?

I need to be able to have nodes dynamically join (with a security key) as there could be many thousands of nodes and adding them manually to a config file will not work for my use case.

Can you please advise?
thanks

**Comment by sjqzhang** [comment]
Go-fastdfs itself don't support dynamically add node to the cluster.  If you want to implements your idea you can add a proxy server like Nginx.   You can refer to the following examples:
https://sjqzhang.gitee.io/go-fastdfs/install.html#big-cluster

**Comment by sjqzhang** [comment]
Go-fastdfs itself don't support dynamically add node to the cluster.  If you want to implements your idea you can add a proxy server like Nginx.   You can refer to the following examples:
https://sjqzhang.gitee.io/go-fastdfs/install.html#big-cluster

**Comment by lonnietc** [comment]
Thanks for answering this question as it will be helpful.

I really like many of the features that your documentation has talked about which if the project great potential.

Other similar projects are SeaweedFS but while they do have dynamic joining of nodes, they do not seem to have many other features that yours has available.
