### ISSUE TITLE
无法跨域上传，不好意思再打开这个问题

### ISSUE THREAD

**Issue by 17661152** [sjqzhang/go-fastdfs#32]
还是无法跨越上传，下载的是最新版本了。v1.2.6 错误信息：X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response. 应该是ajax请求响应的json无法跨域。
看了你源码只设置了allowedOrigins，allowedHeaders也应该设置才对吧？

//设置允许跨域的路径
        registry.addMapping("/**")
                //设置允许跨域请求的域名
                .allowedOrigins("*")
                //设置请求头跨域类型
                //.allowedHeaders("client", "accessToken", "Response-Wrapper")
                //是否允许证书 不再默认开启
                .allowCredentials(true)
                //设置允许的方法
                .allowedMethods("*")
                //跨域允许时间
                .maxAge(18000);

以上是java代码设置跨域访问的示例

**Comment by 17661152** [comment]
"是否开启跨站访问": "默认开启",
	"enable_cross_origin": true, 

配置文件是开启了的

**Comment by sjqzhang** [comment]
好的，你加微信，后面我单独发包你给你验证。

**Comment by 17661152** [comment]
@sjqzhang  我的微信号jack17661152

**Comment by lwj-java** [comment]
> "是否开启跨站访问": "默认开启",
> "enable_cross_origin": true,
> 
> 配置文件是开启了的

请问这个问题，您解决了嘛？
