### ISSUE TITLE
文件上传后能否保留后缀名

### ISSUE THREAD

**Issue by 838239178** [sjqzhang/go-fastdfs#325]
文件直链能否保留后缀

**Comment by sjqzhang** [comment]
默认就保留呀

**Comment by 838239178** [comment]
![屏幕截图 2022-01-15 115312](https://user-images.githubusercontent.com/55338151/149607806-c5b17c21-6f25-487e-8365-0dd5e50eaa8f.png)
@sjqzhang tus协议的没有后缀
