### ISSUE TITLE
cannot find package "." in:

### ISSUE THREAD

**Issue by tanoak10** [sjqzhang/go-fastdfs#326]
使用 goland IDE 
go build -o fileserver fileserver.go
编译，出现
cannot find package "." in:
        D:\go_workspace\src\go-fastdfs\vendor\fileserver.go
源码中
![image](https://user-images.githubusercontent.com/37281126/149712917-da225b33-eeea-4e7c-a14c-63e4104aeea2.png)

**Comment by sjqzhang** [comment]
代码重构了，文档可能没有修改，参阅build.sh
