### ISSUE TITLE
google认证开启后不传验证码依旧可以上传文件

### ISSUE THREAD

**Issue by xiangshibo** [sjqzhang/go-fastdfs#33]
开启验证后，如果在上传地址中不加入场景参数如图：
![image](https://user-images.githubusercontent.com/11767971/55450889-5146dd00-5603-11e9-8717-9f04ec567a30.png)
依旧可以上传成功。并且还是保存在defalut的场景下，只有添加了场景名，如图：
![image](https://user-images.githubusercontent.com/11767971/55457832-bdced580-561d-11e9-93b1-e88e428a7e61.png)

才会提示无效的code。
有没有什么办法，让不传场景名时也能走验证方法呢。
文件配置信息如下：
![image](https://user-images.githubusercontent.com/11767971/55451046-e0ec8b80-5603-11e9-980c-3bd76425a468.png)

**Comment by sjqzhang** [comment]
将默认场景也加入到场景列表中，并增加相应的认证secret，就像你的app那样
