### ISSUE TITLE
Tus上传时，自定义scene参数则奶

### ISSUE THREAD

**Issue by Liu-Junlin** [sjqzhang/go-fastdfs#336]
![image](https://user-images.githubusercontent.com/15389578/158951966-fe3abb9e-333d-40cf-9d5a-b8f2ababbf85.png)

![image](https://user-images.githubusercontent.com/15389578/158952004-9850636b-fff5-4906-9337-d0a6aa39de11.png)

如果不指定scene，则正常上传。

尝试调整以下位置：
![image](https://user-images.githubusercontent.com/15389578/158952292-fd558b41-6a4d-46e0-9e7a-0c86a00b9194.png)
增加文件夹创建，但仍会报leveldb: not found，可能文件在此之前就存库了。
我是搞java的，这个改不动。。。
还望大佬抽时间看下。

**Comment by sjqzhang** [comment]
Tus上传不支持自定义路径。
