### ISSUE TITLE
这个是什么问题 我的go版本是1.17.8

### ISSUE THREAD

**Issue by tutengdihuang** [sjqzhang/go-fastdfs#338]
github.com/sjqzhang/tusd tested by
        github.com/sjqzhang/tusd.test imports
        github.com/tus/tusd: module github.com/tus/tusd@latest found (v1.8.0, replaced by github.com/tus/tusd@v1.8.0), but does not contain package github.com/tus/tusd
github.com/sjqzhang/go-fastdfs/server imports
        github.com/sjqzhang/tusd tested by
        github.com/sjqzhang/tusd.test imports
        github.com/tus/tusd/filestore: module github.com/tus/tusd@latest found (v1.8.0, replaced by github.com/tus/tusd@v1.8.0), but does not contain package github.com/tus/tusd/filestore
github.com/sjqzhang/go-fastdfs/server imports
        github.com/sjqzhang/tusd tested by
        github.com/sjqzhang/tusd.test imports
        github.com/tus/tusd/limitedstore: module github.com/tus/tusd@latest found (v1.8.0, replaced by github.com/tus/tusd@v1.8.0), but does not contain package github.com/tus/tusd/limitedstore
github.com/sjqzhang/go-fastdfs/server imports
        github.com/sjqzhang/tusd tested by
        github.com/sjqzhang/tusd.test imports
        github.com/tus/tusd/memorylocker: module github.com/tus/tusd@latest found (v1.8.0, replaced by github.com/tus/tusd@v1.8.0), but does not contain package github.com/tus/tusd/memorylocker

**Comment by sjqzhang** [comment]
有些包可能更新了，可以参考build.sh
