### ISSUE TITLE
询问一下去中心化原理

### ISSUE THREAD

**Issue by 838239178** [sjqzhang/go-fastdfs#339]
去中心化是如何保证文件可以平均分配到每个节点？访问的时候如何定位到文件的位置？备份是采用互相备份的方式吗？备份位置信息是在每个节点上同步吗？

小白最近在学这方面知识，对这个项目一直挺感兴趣，如果可以解惑那么感激不尽。

**Comment by sjqzhang** [comment]
集群内节点是全对等（内容完全一样，冗余），去中心化是指文件系统没有中心的协调器，由用户决定访问那个集群（URL中带有集群信息）。
