### ISSUE TITLE
如何自定义文件存放路径

### ISSUE THREAD

**Issue by xiangshibo** [sjqzhang/go-fastdfs#34]
目前文件存放在go-fastDFS的安装目录下。可不可以放在自定义的路径下。设置了GO_FASTDFS_DIR环境变量后没有任何反应，环境变量配置如下：
![image](https://user-images.githubusercontent.com/11767971/55773770-c8c5b200-5ac4-11e9-99db-2311d9ddbd46.png)

**Comment by sjqzhang** [comment]
启动时设定环境变量

**Comment by xiangshibo** [comment]
在启动时指定了环境变量，会重新生成配置文件等信息，这样的话是不是我如果之前在另外一个路径上存有文件的话，是不是就无法访问了呢。比如：开始在A路径上存放文件，后来改到了B路径。此时使用的是B路径下的配置文件，这时候是不是就没有办法再访问到A下面的文件了呢

**Comment by xiangshibo** [comment]
> 启动时设定环境变量

在启动时指定了环境变量，会重新生成配置文件等信息，这样的话是不是我如果之前在另外一个路径上存有文件的话，是不是就无法访问了呢比如：开始在甲路径上存放文件，后来改到了乙路径。此时使用的是乙路径下的配置文件，这时候是不是就没有办法再访问到甲下面的文件了呢
