### ISSUE TITLE
做性能测试时文件下载报错问题

### ISSUE THREAD

**Issue by VegetableCoder-yf** [sjqzhang/go-fastdfs#342]
断点续传上传的图片显示是成功的，但是查看gofastdfs保存的图片是不完整的，比如有的图片只显示了一般。然后下载图片时报错。下面是日志。
日志打印如下：2022-04-14 15:38:59 [ERR] [fileserver.go:1417] [gofd.(*Server).ResizeImage] png: invalid format: invalid checksum
通过url地址打开图片后，解码失败了。这个报错一般会是什么原因导致的

**Comment by sjqzhang** [comment]
上传成功要置换正常的url,先看看能不能置换url
