### ISSUE TITLE
在 download_domain 添加了域名，该如何在 nginx 中配置，我才能访问到文件呢？

### ISSUE THREAD

**Issue by zhgt-shaozi** [sjqzhang/go-fastdfs#346]
go-fastdfs 配置项
![image](https://user-images.githubusercontent.com/39938981/168534785-af688903-7dee-4947-98ca-264411280ab0.png)

使用 go-fastdfs 上传好的图片链接如下:
`https://aone-time.icu/group1/default/20220516/12/42/7/wallhaven-pkw6y3_1920x1080.png`

访问该链接，都会报 404 的错误，应该是 nginx 配置不对，请教下该怎么配才能访问到呢;

我的 nginx 配置项如下
```
http {
  #....

 upstream go-fastdfs {
        server 81.70.239.170:8081;
        ip_hash;
  } 

  server {
       # ...
       listen 80;
       listen 443 ssl http2;
       server_name   aone-time.icu
       #....
  
       # 访问 go-fastdfs 上传好的服务器中的文件
      location ~ /group([0-9]) {
         proxy-pass    http://go-fastdfs;
          root    /home/gofastdfs/files;
      }
  }

}
```

**Comment by sjqzhang** [comment]
这个只能自查nginx资料，表示帮不了。
