### ISSUE TITLE
集群上传成功，下载失败

### ISSUE THREAD

**Issue by koo1357** [sjqzhang/go-fastdfs#347]
nginx配置如下：

#user  nobody;
worker_processes  auto;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
error_log  logs/error.log  debug;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/html;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    map $http_upgrade $connection_upgrade { 
        default          keep-alive;
        'websocket'      upgrade;
    }

    rewrite_log on;
    client_max_body_size 0;
    proxy_redirect ~/(\w+)/big/upload/(.*) /$1/big/upload/$2;  #继点续传一定要设置(注意)
    
    upstream group1 {
                server 172.31.32.50:9013;
                server 172.31.32.52:9883;
                ip_hash;     #notice:very important(注意)
    }

    server {
                listen       9885;
                server_name  172.31.32.52;

	charset utf-8;
	if ( $request_uri ~ /godfs/group ) {
                    # 注意group会随组的前缀改变而改变
            rewrite ^/godfs/(.*)$ /$1 last;
                }
                location ~ /group(\d) { 
                    #统一在url前增加godfs,以便统一出入口。
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
                    proxy_pass http://group$1;
                }
                location ~ /godfs/upload { 
                    #这是一个横向扩展配置，前期可能只有一个集群group1,当group1满后，只需将上传指向group2,
                    #也就是将rewrite , proxy_pass 中的group1改为group2即可。
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
                    rewrite ^/godfs/upload /group1/upload break;
                    proxy_pass http://group1;
                }
                location ~ /godfs/big/upload { 
                    #以上上类似。
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
                    rewrite ^/godfs/upload /group1/big/upload break;
                    proxy_pass http://group1;
                }
		
		location / {
		    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
                    proxy_pass http://group$1;
		}
        }

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   /opt/html/robot-chat;
            try_files $uri $uri/ /robot-chat/index.html;
            index  index.html index.htm;
        }
	
	location /consultant-end {
	    alias /opt/html/robot-chat;
	    try_files $uri $uri/ /robot-chat/index.html;
	    index index.html index.htm;
	}

        location /robot-ui{
            alias   /opt/html/robot-ui;
            try_files $uri $uri/ /robot-ui/index.html;
            index  index.html index.htm;
        }
        

	#location /robot-gateway {
	#    if   ($request_method =   'OPTIONS') {
        #	return 204;
   	#     }
        #    proxy_pass http://172.31.32.50:9100;
        #    proxy_set_header   Host    $host;
	#    proxy_set_header   X-Real-IP   $remote_addr;
    	#    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
	#}

        location /robot-gateway/ {
    	    if   ($request_method =   'OPTIONS') {
	        return 204;
	    }

            proxy_pass http://172.31.32.50:9100;
            proxy_http_version 1.1;
	    proxy_set_header Upgrade $http_upgrade;
    	    proxy_set_header Connection $connection_upgrade;
	}

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }

    include conf/*.conf;
}

**Comment by sjqzhang** [comment]
你确认一下没有nginx是否正常，如果正常，只能你自己查资料解决nginx配置问题。
