### ISSUE TITLE
每次运行go mod tidy出错

### ISSUE THREAD

**Issue by xiaoshengduan** [sjqzhang/go-fastdfs#354]
github.com/sjqzhang/tusd tested by
        github.com/sjqzhang/tusd.test imports
        github.com/tus/tusd/memorylocker: module github.com/tus/tusd@latest found (v1.9.0), but does not contain package github.com/tus/tusd/memorylocker

 github.com/sjqzhang/tusd tested by
        github.com/sjqzhang/tusd.test imports
        github.com/tus/tusd/limitedstore: module github.com/tus/tusd@latest found (v1.9.0), but does not contain package github.com/tus/tusd/limitedstore

**Comment by sjqzhang** [comment]
请更新go.mod再试试，或者参与 build.sh 的方式构建。
