### ISSUE TITLE
请问自动修复和同步失败的重试是一个概念吗？

### ISSUE THREAD

**Issue by nwpuqyj** [sjqzhang/go-fastdfs#357]
想请教下，自动修复和同步失败重试是一个概念吗？我在配置文件中关闭了自动修复，但是在指定时间后，依然会进行同步失败的重试。没太理解配置文件中的自动修复功能

**Comment by sjqzhang** [comment]
应该是你的集群配置问题，可以认真阅读配置文件，自己多动手试试，选项太多，需要自己理解一下。
