### ISSUE TITLE
自从用了1.4.3版本后, 多台gofast集群,运行一段时间后经常遇到某个服务器的go-fastdfs进程打开文件数干满，tcp队列堵塞导致服务不可用，最后只能重启服务，请问怎么解决这个bug？

### ISSUE THREAD

**Issue by xjzyy** [sjqzhang/go-fastdfs#366]
自从用了1.4.3版本后, 多台gofast集群,运行一段时间后经常遇到某个服务器的go-fastdfs进程打开文件数干满，tcp队列堵塞导致服务不可用，最后只能重启服务，请问怎么解决这个bug？

http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 1s

[ERR] [fileserver.go:1131] [github.com/sjqzhang/go-fastdfs/server.(*Server).CheckClusterStatus.func1] Get http://xx.xx.xx.xx:9000/group1/status: dial tcp xx.xx.xx.xx:9000: socket: too many open files

**Comment by sjqzhang** [comment]
ulimit -n 看看是多少，具体可以网上找资料怎么处理

**Comment by xjzyy** [comment]
> ulimit -n 看看是多少，具体可以在网上找资料怎么处理

ulimit -n：65535  

系统：Alibaba Cloud Linux release 3 (Soaring Falcon)

此问题已经多次重现了，没有找到解决办法，每次都是把负载那边权重改0 然后重启。。。

之前用旧版本就没出现过，迁移集群直接升了最新版本，3台除了第一个节点正常外，其余2节点经常出现这个问题。

**Comment by johnniuzi** [comment]
我也碰到了该问题，现在每天需要重启两次集群才能支撑。
并且，在重启集群后，还会自动删除几个文件。
不知道是否有其他朋友遇到这个问题。

**Comment by rea-leaf** [comment]
大佬这个问题最后是怎么解决的

> 我也碰到了该问题，现在每天需要重启两次集群才能支撑。 并且，在重启集群后，还会自动删除几个文件。 不知道是否有其他朋友遇到这个问题。
