### ISSUE TITLE
tus上传关闭了enable_distinct_file也会校验md5，导致文件不会上传，而是依然使用之前的地址

### ISSUE THREAD

**Issue by zklyzhoutao** [sjqzhang/go-fastdfs#368]
看了下源码，在initTus处增加了enable_distinct_file判断，这样使用tus就可以重新上传同样的文件了.

**Comment by sjqzhang** [comment]
使用tus上传的，大部分都是大文件，为了减少空间浪费，对于大文件都使用去重设计。
