### ISSUE TITLE
windows server2008R2，以相对路径启动成功后访问时404错误

### ISSUE THREAD

**Issue by chengyuansen** [sjqzhang/go-fastdfs#37]
操作系统：windows server2008R2 Standard ，Service Pack1。
fastdfs版本：V1.2.7
问题描述：
fileserver.exe存储路径为D:\go-fastdfs\fileserver.exe，打开命令行，切换到D:\go-fastdfs路径下，然后fileserver.exe启动。启动成功后访问http://localhost:8080，结果返回：404 page not found

fileserver.exe存储路径不变，不管当前路径是什么，直接复制fileserver.exe全路径，例如：D:\go-fastdfs\fileserver.exe，然后回车启动。启动成功后访问http://localhost:8080，访问成功。

结论：
windows server2008R2 Standard ，Service Pack1环境下，fileserver.exe绝对路径启动访问成功，但相对路径启动则404。
但windows10 professional版，无论绝对路径还是相对路径，都是OK的。

**Comment by chengyuansen** [comment]
access.log和fileserver.log都没有异常。

**Comment by sjqzhang** [comment]
配置问题，看q & a
