### ISSUE TITLE
对应/data/fastdfs_data/files下还存在文件 但是del接口却无法删除文件

### ISSUE THREAD

**Issue by ycshoyoo** [sjqzhang/go-fastdfs#377]
使用path参数进行删除 path路径正确，但是接口返回fail
{
  "data": null,
  "message": "leveldb: not found",
  "status": "fail"
}

背景：压测时对对应的容器设置了内存限制，当容器内存达到阈值那么后面删除文件就会报这个错误

**Comment by sjqzhang** [comment]
没有复现，请给出详细操作步骤。
