### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by wys1010** [sjqzhang/go-fastdfs#378]
可能是kill -9杀进程的原因导致启动不了，报如下错误：
```
open db file data/fileserver.db fail,maybe has opening
panic: file missing [file=MANIFEST-000000]
```

第一反应上github上找原因，其中就有人遇到过（#222 ），说要删除data目录才能修复，于是我也这么干了，导致之前的文件都访问不了，正式环境上的，非常重要，请问要怎么修复？我现在头都大了。删除data之前我有备份

**Comment by sjqzhang** [comment]
删除data也不会影响访问，至于上面的报错，主要是因为二次启动或文件二次被打开引起，自已检查一下。
