### ISSUE TITLE
文件反复同步

### ISSUE THREAD

**Issue by CTFer** [sjqzhang/go-fastdfs#379]
文件存在反复同步的问题，集群由三台服务器构成，通常会上传到A机器，B、C机器自动同步。但是现在总是出现文件反复同步的问题。
![微信图片_20230123122950](https://user-images.githubusercontent.com/16458937/213966239-13dd72ae-709d-4b3b-a529-e18781f7aa5d.jpg)
![微信图片_20230123122955](https://user-images.githubusercontent.com/16458937/213966257-c4892d68-398e-4779-b90c-7eb27ceccc05.jpg)

**Comment by sjqzhang** [comment]
可以从不同的节点下载看看能不能下载到文件，以及下载需要多久，检查一下是不是下载同步过程中超时，导致同步不成功反复进行同步。
