### ISSUE TITLE
buffer full

### ISSUE THREAD

**Issue by ytt521** [sjqzhang/go-fastdfs#381]
java代码上传350个文件时（文件总大小150G，每个文件最大1G），报错multipart: NextPart: bufio: buffer full

**Comment by sjqzhang** [comment]
可以用内置的压测程序试一下，验证一下是不是go-fastdfs本身问题，并截图看看。

**Comment by ytt521** [comment]
您好，我使用了压测的python脚本，生成了20个文件夹的数据，每个文件夹里有10个文件，单个不超过600M（大概都是530M左右），执行压测python脚本，服务器运行内存直接拉满了，python命令被killed了，如果在java代码里上传这些文件（hutool方式），会导致后续的上传请求出问题吗，压测的时候没有看到buffer full的报错（因为被kill），这个bufio在哪里用到了呢

**Comment by sjqzhang** [comment]
看一下帮助视频，使用go版本的压测工具进行压测，看看是什么样的情况
