### ISSUE TITLE
启动失败问题

### ISSUE THREAD

**Issue by songjunbiao** [sjqzhang/go-fastdfs#382]
./fileserver 
panic: http: multiple registrations for /

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0xea1080, 0xe674ef, 0x1, 0xac49a0, 0xc000711490)
	/usr/local/go/src/net/http/server.go:2377 +0x221
net/http.(*ServeMux).HandleFunc(0xea1080, 0xe674ef, 0x1, 0xc000711490)
	/usr/local/go/src/net/http/server.go:2395 +0x5a
net/http.HandleFunc(0xe674ef, 0x1, 0xc000711490)
	/usr/local/go/src/net/http/server.go:2407 +0x4b
main.(*Server).Main(0xc000490000)
	/opt/go-fastdfs/fileserver.go:4276 +0x227a
main.main()
	/opt/go-fastdfs/fileserver.go:4316 +0x2d
提示这个一起启动失败 需要怎样解决呢

**Comment by sjqzhang** [comment]
应该是配置问题引起的Bug，可以检查一下配置，或重新生成配置试试。

**Comment by songjunbiao** [comment]
已解决了

**Comment by songjunbiao** [comment]
pid 的问题
