### ISSUE TITLE
集群自动同步失败

### ISSUE THREAD

**Issue by liuxinglan13** [sjqzhang/go-fastdfs#383]
A B两台服务器文件数量不同步，A：1145  B：360   ，执行 http://127.0.0.1:8080/repair?force=1 修复没有效果。

请问该如何排错？

{
	"绑定端号": "端口",
	"addr": ":8080",
	"是否开启https": "默认不开启，如需启开启，请在conf目录中增加证书文件 server.crt 私钥 文件 server.key",
	"enable_https": true,
	"PeerID": "集群内唯一,请使用0-9的单字符，默认自动生成",
	"peer_id": "6",
	"本主机地址": "本机http地址,默认自动生成(注意端口必须与addr中的端口一致），必段为内网，自动生成不为内网请自行修改，下同",
	"host": "http://172.16.85.54:8080",
	"集群": "集群列表,注意为了高可用，IP必须不能是同一个,同一不会自动备份，且不能为127.0.0.1,且必须为内网IP，默认自动生成",
	"peers": ["http://172.16.85.54:8080","http://172.16.85.55:8080"],
	"组号": "用于区别不同的集群(上传或下载)与support_group_manage配合使用,带在下载路径中",
	"group": "group1",
	"是否支持按组（集群）管理,主要用途是Nginx支持多集群": "默认支持,不支持时路径为http://10.1.5.4:8080/action,支持时为http://10.1.5.4:8080/group(配置中的group参数)/action,action为动作名，如status,delete,sync等",
	"support_group_manage": true,
	"是否合并小文件": "默认不合并,合并可以解决inode不够用的情况（当前对于小于1M文件）进行合并",
	"enable_merge_small_file": false,
	"图片是否缩放": "默认是",
	"enable_image_resize": true,
	"图片最大宽度": "默认值2000",
	"image_max_width": 2000,
	"图片最大高度": "默认值1000",
	"image_max_height": 1000,
    "允许后缀名": "允许可以上传的文件后缀名，如jpg,jpeg,png等。留空允许所有。",
	"extensions": [],
	"重试同步失败文件的时间": "单位秒",
	"refresh_interval": 1800,
	"是否自动重命名": "默认不自动重命名,使用原文件名",
	"rename_file": true,
	"是否支持web上传,方便调试": "默认支持web上传",
	"enable_web_upload": true,
	"enable_pprof_debug": false,
	"是否支持非日期路径": "默认支持非日期路径,也即支持自定义路径,需要上传文件时指定path",
	"enable_custom_path": true,
	"下载域名": "用于外网下载文件的域名",
	"download_domain": "erp-file.rokin.cn:8080",
	"场景列表": "当设定后，用户指的场景必项在列表中，默认不做限制(注意：如果想开启场景认功能，格式如下：'场景名:googleauth_secret' 如 default:N7IET373HB2C5M6D ",

**Comment by sjqzhang** [comment]
观看一下视频教程，检查配置。

**Comment by liuxinglan13** [comment]
Get https://172.16.85.55:8080/group1/status: x509: cannot validate certificate for 172.16.85.55 because it doesn't contain any IP SANs

是不是因为我 在go-fastdfs开启了 https?
"peers": ["https://172.16.85.54:8080","https://172.16.85.55:8080"],

还是说 最好把证书放在nginx？

**Comment by liuxinglan13** [comment]
> 查一下日志看有没有异常，观看一下视频教程，检查配置。

Get https://172.16.85.55:8080/group1/status: x509: cannot validate certificate for 172.16.85.55 because it doesn't contain any IP SANs

是不是因为我 在go-fastdfs开启了 https?
"peers": ["https://172.16.85.54:8080","https://172.16.85.55:8080"],

还是说 最好把证书放在nginx？

**Comment by sjqzhang** [comment]
是的，证书放nginx
