### ISSUE TITLE
迁移files目录至新服务器后，如何确认迁移是否完成？

### ISSUE THREAD

**Issue by liuxinglan13** [sjqzhang/go-fastdfs#384]
尝试将 files目录复制到新服务器后，
1.修改配置文件 "enable_migrate": true,重启服务
2.这个时候如何确定迁移完成?什么时候再把 配置改回false
3. 通过api查看 stat 没有信息
4. 手动动过脚本一天一天刷新了统计信息，api能自动统计所有信息嘛？

 #!/bin/bash

start_date=2022-06-29
end_date=2023-02-03

start_date_in_seconds=$(date -d "$start_date" +%s)
end_date_in_seconds=$(date -d "$end_date" +%s)

for ((i=start_date_in_seconds; i<=end_date_in_seconds; i+=86400)); do
    date_in_format=$(date -d @$i +%Y%m%d)
    curl http://172.16.89.42:8080/group1/repair_stat?date=$date_in_format
done

**Comment by sjqzhang** [comment]
如果你是按照系统自动生成的的目录结构，是可以通过按日期统计比对文件数量判断是否同步完成的，这也是内部同步机制的一部分。
