### ISSUE TITLE
nginx反向代理集群的返回参数 问题

### ISSUE THREAD

**Issue by dupeng321** [sjqzhang/go-fastdfs#386]
你好， 通过nginx反向代理文件服务器集群来上传文件的方式，返回的参数中 url  和 domain 字段 中没有实际文件存储服务器的ip:port  信息，代替的是nginx所在服务器的ip ;

**Comment by sjqzhang** [comment]
可以在配置文件中配置，可以观看一下视频教程。

**Comment by dupeng321** [comment]
你好, 请问是cfg.json 配置文件吗？ 看了5分多钟的视频教程，不是很清楚这个问题应该怎么配置？


我再描叙一下情况：


1）在单节点测试，没有使用nginx代理时， clent ---&gt; fileserver 模式, 上传文件的返回参数中 url 和 domain里面 包含了 fileserver 的 ip:port 信息；


2）参照文档中 小集群 和 海量集群安装，引入nginx代理， client ---&gt; nginx ---&gt; fileserver 模式 , 上传文件返回的参数中 url 和 domain里面 没有 fileserver 的 ip:port 信息 ，而是&nbsp; nginx 所在服务器的 ip (没有端口，默认80）， 这样client 想通过返回的 url 无法直接 访问到该文件 。是否需要在nginx 中做一些什么配置呢？





谢谢！
dupeng

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sjqzhang/go-fastdfs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月7日(星期二) 下午3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sjqzhang/go-fastdfs] nginx反向代理集群的返回参数 问题 (Issue #386)





 
可以在配置文件中配置，可以观看一下视频教程。

**Comment by sjqzhang** [comment]
使用download_domain配置项进行配置
