### ISSUE TITLE
一台正常，另一台连接不到，显示连接被拒绝

### ISSUE THREAD

**Issue by rxl19990103** [sjqzhang/go-fastdfs#389]

**Comment by rxl19990103** [comment]
get “http:/localhost:10909/group1/status”:dial tcp IP:10909 : connect : conntction refused

**Comment by rxl19990103** [comment]
当前无文件上传，但是过一段时间会突然说一台连接不上另一台，看了fileserver.log 中，一台是没有报错信息，另一台就报错：连接被拒绝

**Comment by sjqzhang** [comment]
conntction refused 应该是服务没有启动，检查一下服务及配置，建议看一下视频教程，可以少走一些弯路。
