### ISSUE TITLE
集群模式上传文件后无法通过生成的链接访问文件

### ISSUE THREAD

**Issue by rexlibing** [sjqzhang/go-fastdfs#39]
集群模式上传上去后无法通过生成的链接访问文件，这样不太好吧，生产环境还是要求快速同步比较好吧？如何配置快速同步。还有如何检查gofastdfs集群是否正常工作？感觉是peer是各自为政。

**Comment by sjqzhang** [comment]
应该没有这个问题才对，用的是什么版本？

**Comment by rexlibing** [comment]
最新版的1.2.7 ，是不是我的配置文件写错地方了。我写在主目录下fileserver.go这个配置文件中的，是不是应该写在conf/cfg.json中。

**Comment by sjqzhang** [comment]
是你写错了

**Comment by rexlibing** [comment]
哪个群啊？

**Comment by rexlibing** [comment]
看到了
