### ISSUE TITLE
大文件断点续传和普通上传的自定义验证方式返回结果校验逻辑不统一

### ISSUE THREAD

**Issue by Succy** [sjqzhang/go-fastdfs#395]
在go-fastdfs里面支持自定义认证，但是经过排查发现使用tusd的断点续传和普通文件上传进行自定义认证时，对返回的结果校验逻辑不统一的问题。
> **普通上传**的认证，参考`http_upload.go`中对`CheckAuth`的返回结果校验，如下图

![image](https://user-images.githubusercontent.com/20968762/231028385-8255df45-eb5c-43f9-a3bb-46a5870df196.png)
> **Tusd文件上传**的认证，参考`store.go`对返回结果的校验，如下图

![image](https://user-images.githubusercontent.com/20968762/231028563-073b6bd5-9f47-4b58-b7dd-4b5bb920cde8.png)

从上面两个截图不难看出，普通上传校验的是`status`字段是否是为`fail`，如果非`fail`的都认为成功，但是在tusd的上传校验中，则是验证`data`字段内容是否为`ok`，不为ok则认为不成功，因此，验证的字段和验证的逻辑都不同，在同一套验证机制下，必定有一个是通过不了，缺乏一定严谨性，望修改。

**Comment by sjqzhang** [comment]
没有找到相关代码段，这是不是老代码？
<img width="779" alt="image" src="https://user-images.githubusercontent.com/5069242/232471554-1e9140a1-eb29-460e-98d8-3f2da4385106.png">
新的代码返回的是bool类型
