### ISSUE TITLE
文件同步问题

### ISSUE THREAD

**Issue by ytt521** [sjqzhang/go-fastdfs#397]
您好，最近在做这样的一件事情，可不可以直接将文件写入到files文件夹，然后拓展一些接口出来，类似于官方提供的文件同步接口，上传完后，手动同步文件的元数据到leveldb中，同时调用修复统计信息接口进行统计信息的修复，您看看这个思路有没有什么问题，或者是哪里有欠缺呢？

**Comment by sjqzhang** [comment]
![image](https://user-images.githubusercontent.com/5069242/231470608-49085a2c-8a2c-40fd-a7ea-bd13a90b1348.png)
可以了解一下这几个repair接口
