### ISSUE TITLE
2台机器的集群一台挂掉的情况下，在另外一台上上传文件，重启后不会自动同步

### ISSUE THREAD

**Issue by chengyuansen** [sjqzhang/go-fastdfs#4]
2台机器的集群一台挂掉的情况下，在另外一台上上传文件。挂掉的server重新启动后没有自动同步数据。这个也需要手动同步吗？最好是自动同步吧？

**Comment by sjqzhang** [comment]
自动同步只限示当天的文件，并且在上传文件之前，机器是同一个集群的情况下同自动同步，即使不同步也不影响文件的访问，在访问时会自动修复不同步的文件。

**Comment by sjqzhang** [comment]
已修复，请验证一下是否生效，需要在配置文件中增加了  "auto_repair":true
