### ISSUE TITLE
断点下载配置问题

### ISSUE THREAD

**Issue by swiftsnail001** [sjqzhang/go-fastdfs#400]
目前服务器端HTTP下载 默认传输编码方式为chunked，通过测试无法断点下载。
请问下如何配置才能断点下载，多谢

**Comment by sjqzhang** [comment]
无需设置，参与linux wget  -c 命令设置相应的http头就OK。

**Comment by swiftsnail001** [comment]
你好，目前测试普通文件的上传和断点下载是可以的。
   但是如果是大文件上传，走的是group1/big/upload这个路径，后面再下载的时候，HTTP的传输编码为chunked方式，此时好像不能断点下载了，麻烦帮解答下，谢谢！
