### ISSUE TITLE
服务器断点下载问题

### ISSUE THREAD

**Issue by swiftsnail001** [sjqzhang/go-fastdfs#401]
你好，目前测试普通文件的上传和断点下载是可以的。
但是如果是大文件上传，走的是group1/big/upload这个路径，后面再下载的时候，HTTP的传输编码为chunked方式，此时好像不能断点下载了，麻烦帮解答下，谢谢！
还有个问题，就是普通上传支持断点上传吗？？

**Comment by sjqzhang** [comment]
大文件上传后记得要好路径置换，路径转换后可以进么断点续传，普通文件不支持断点上传，我印象文档或视频教程里有介绍，自已查阅一下。
