### ISSUE TITLE
大文件路径转换问题

### ISSUE THREAD

**Issue by swiftsnail001** [sjqzhang/go-fastdfs#402]
目前使用中发现，通过大文件方式上传文件后，在服务器在回复204代表上传文件成功，此时立即通过文件秒传接口进行路径转换，返回的结果是空的。
 需要等待一段时间，再次请求路径转换接口，才能返回正常的结果。
这个是不是有性能问题？或者说什么时候才能进行路径转换？

**Comment by sjqzhang** [comment]
上传成功，等一段时间是因为系统在转存，可以通过回调，具体参考内置上传页面的方法。
