### ISSUE TITLE
动态加载配置文件失败

### ISSUE THREAD

**Issue by PantsuDango** [sjqzhang/go-fastdfs#403]
sh-4.2# curl http://127.0.0.1:8080/reload
(error)action support set(json) get reload

**Comment by sjqzhang** [comment]
可能因为安全问题，印象中新版本的做了功能限制

**Comment by PantsuDango** [comment]
> 大哥这个问题怎么解决的啊？咱也遇到了。本机调用也报这个错

我没解决，没继续纠结了，感觉是被禁止使用这个命令了。我直接改配置文件然后重启服务这样操作了
