### ISSUE TITLE
上传文件后返回domain中不包含端口

### ISSUE THREAD

**Issue by wangyuanchen** [sjqzhang/go-fastdfs#406]
{
  "data": {
    "domain": "http://43.111.222.22",
    "md5": "571058cd7a7eb244a052de672984b667",
    "mtime": 1685066397,
    "path": "/group1/robotconfig/d1ea50f8-e318-472e-85d0-1dd22e3ead51/origin/111.txt",
    "retcode": 0,
    "retmsg": "",
    "scene": "robotconfig",
    "scenes": "robotconfig",
    "size": 518,
    "src": "/group1/robotconfig/d1ea50f8-e318-472e-85d0-1dd22e3ead51/origin/111.txt",
    "url": "http://43.143.223.22/group1/robotconfig/d1ea50f8-e318-472e-85d0-1dd22e3ead51/origin/111.txt?name=111.txt&download=1"
  },
  "message": "",
  "status": "ok"
}

但是，测试没有加nginx的情况下是有的
{
  "data": {
    "domain": "http://1.11.11.111:8080",
    "md5": "ab655b1e32f4844f783b81f642ccec6e",
    "mtime": 1685006305,
    "path": "/group1/robotconfig/d1ea50f8-e318-472e-85d0-1dd22e3ead51/origin/问题1.txt",
    "retcode": 0,
    "retmsg": "",
    "scene": "robotconfig",
    "scenes": "robotconfig",
    "size": 516,
    "src": "/group1/robotconfig/d1ea50f8-e318-472e-85d0-1dd22e3ead51/origin/问题1.txt",
    "url": "http://1.13.24.50:8080/group1/robotconfig/d1ea50f8-e318-472e-85d0-1dd22e3ead51/origin/问题1.txt?name=%E9%97%AE%E9%A2%981.txt&download=1"
  },
  "message": "",
  "status": "ok"
}

出现这个现象的问题是？

**Comment by sjqzhang** [comment]
可以在配置中配置。具体看配置说明。
