### ISSUE TITLE
部署了fileserver无法从同一局域网下的其他IP访问服务器下载文件

### ISSUE THREAD

**Issue by conjurer-123** [sjqzhang/go-fastdfs#409]
目前仅部署了fileserver，使用的8080端口，本机浏览器可访问和下载文件，但其他IP的浏览器不行，请教一下是否还需要部署其他部件？
我的需求就是简单搭一个文件服务器，提供同一局域网段内的访问和下载。请大神帮忙解答一下，谢谢。

**Comment by sjqzhang** [comment]
这是基本功能，IP需要在其它电脑可访问，看一下视频教程
