### ISSUE TITLE
添加nginx代理，upload返回404

### ISSUE THREAD

**Issue by happyycm** [sjqzhang/go-fastdfs#41]
版本1.2.7

因为端口的问题， 添加了一个nginx前置，相关Nginx配置如下

```
location /files 
{
        proxy_pass http://127.0.0.1:8080/;
}
```

其中8080是go-fastdfs的端口

现在直接访问http://mydomain/files  会打开默认的上传WEB测试界面

但是访问http://mydomain/files/upload会返回404 Not Found

是Nginx还需要别的特殊配置吗？

**Comment by sjqzhang** [comment]
配置问题
