### ISSUE TITLE
tmp下的文件恢复

### ISSUE THREAD

**Issue by ytt521** [sjqzhang/go-fastdfs#414]
您好  请问tmp文件夹下的临时文件可以恢复成数据文件存储到files目录下吗
因为我发现我的tmp文件夹下有好多碎片没有上传成功

**Comment by ytt521** [comment]
大概有20T的数据在_tmp下

**Comment by sjqzhang** [comment]
不可以，tmp有这么多数据应该是不正常的，看是使用不当造成，还是版本过旧问题引发？可以升级看看问题是否解决。

**Comment by ytt521** [comment]
如果服务在上传过程中被重启，那_tmp文件夹下的碎片文件会做处理吗？
