### ISSUE TITLE
老师，请问可以使集群上传的文件的Lastmodify保持一致吗？

### ISSUE THREAD

**Issue by nothingbj** [sjqzhang/go-fastdfs#415]
老师，背景是这样的。我们现在是集群的静态资源，然后我们又走CDN了，CDN那边回源策略是判断Lastmodify，如果Lastmodify不一致就回源。现在发现我们集群的相同文件的Lastmodify不一样。这就导致CDN以为要回源了。

**Comment by sjqzhang** [comment]
内部也会通过Lastmodify进行同步判断，不知会不会引出同步异常问题，暂时不会对块逻辑进行修改。
