### ISSUE TITLE
tmp目录在服务重启后会有默认处理吗

### ISSUE THREAD

**Issue by ytt521** [sjqzhang/go-fastdfs#416]
您好，请问如果在上传过程中，gofast服务被停止掉了，过一段时间后重启gofast服务，在重启时会对tmp文件夹做默认处理吗？比如清除？或者继续读取tmp下的文件继续上传？

**Comment by ytt521** [comment]
或者说tmp目录除了文件上传完后自动清除，有没有其他的清除策略？比如gofast会定期清除？

**Comment by sjqzhang** [comment]
理论上，上传完会立即删除的，没有删除应该是出现异常的情况，或者程序存在不确定的bug
