### ISSUE TITLE
如何升级更新？

### ISSUE THREAD

**Issue by 6LWa6ZKx** [sjqzhang/go-fastdfs#417]
你好，直接下载fileserver覆盖重启吗？

文档没有对这块进行描述。

**Comment by sjqzhang** [comment]
是的，直接覆盖，升级时最好备份一下原来的fileserver，以防万一。

**Comment by 6LWa6ZKx** [comment]
> 是的，直接覆盖，升级时最好备份一下原来的fileserver，以防万一。

好的，感谢作者
