### ISSUE TITLE
上传文件显示http no such file

### ISSUE THREAD

**Issue by zengziqiang** [sjqzhang/go-fastdfs#418]
版本1.4.5
按照官网的api示例上传图片，显示如下错误
执行的方法：
![image](https://github.com/sjqzhang/go-fastdfs/assets/18276749/11ab90b3-a480-42f2-b3f6-5e52b50bc30b)

`    @PostMapping("/up3")
    public Rest uploadFiles3(MultipartFile file) {
        String url = "http://192.168.90.105:16000/group1/upload";
        try {
            InputStreamResource isr = new InputStreamResource(file.getInputStream(),
                    file.getOriginalFilename());
            Map<String, Object> params = new HashMap<>();
            params.put("file", isr);
            params.put("path", "86501729");
            params.put("output", "json");
            // String resp = HttpUtil.post(url, params);
            HttpResponse execute = HttpUtil.createPost(url).header("Content-Type", "multipart/form-data").form(params).execute();
            log.info(execute.body());
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }`
报错信息：
![image](https://github.com/sjqzhang/go-fastdfs/assets/18276749/340721b8-2431-498d-b2d6-53ae4d96fbbd)

`{
  "message": "http: no such file",
  "status": "fail",
  "data": null
}`

换成以下方法上传也是一样：
`String resp = HttpUtil.post(url, params);`

**Comment by sjqzhang** [comment]
参考帮助文档。
