### ISSUE TITLE
fileserver.go异常打印语句调整

### ISSUE THREAD

**Issue by wansongying** [sjqzhang/go-fastdfs#429]
Hi，fileserver.go中第308行 return nil, true, errors.New("noFound")建议调整为： return nil, true, errors.New("Not found")。如合适，请采纳，谢谢。

**Comment by sjqzhang** [comment]
已改，自行编译一下。

**Comment by wansongying** [comment]
收到，十分感谢


发自我的 iPhone

在 2023年10月31日，16:16，小张 ***@***.***> 写道：

﻿

已改，自行编译一下。
