### ISSUE TITLE
一些使用上的疑问 

### ISSUE THREAD

**Issue by zengjq13** [sjqzhang/go-fastdfs#434]
① docker hub最新版本：【v1.4.5】   wiki上的最新版本更新记录：【v1.3.1】。那docker hub跟go-fastdfs版本对应关系是什么
② 目前能实现文件查看、下载的链接在几个小时内过期吗，咱系统的认证auth_toke过期时间是多久呢，是永久的吗 
③ docker部署项目 能否通过docker run 中的-e指令去传入【参数】，而不需要去容器内修改配置文件

**Comment by sjqzhang** [comment]
1）可以使用自带的dockerfile自行编译
2）默认是10分钟左右过期
3）暂时不支持
