### ISSUE TITLE
关于docker部署

### ISSUE THREAD

**Issue by xxxmoonquake-dxq** [sjqzhang/go-fastdfs#435]
![image](https://github.com/sjqzhang/go-fastdfs/assets/147611612/94b0a475-3f82-404d-82e9-363d9cdf8cfb)
docker上其他服务器运转都正常，
![image](https://github.com/sjqzhang/go-fastdfs/assets/147611612/9a10978b-3020-4c1d-acba-22343feed86c)
日志显示端口监听也是正常的，求解答

**Comment by sjqzhang** [comment]
看一下视频教程，localhost是容器的ip,如需直接访问，网络模式要改为host模式，具体查阅docker相关文档
