### ISSUE TITLE
您好上传文件后会返回一个json信息，如果想要查询历史文件的json（上传后返回的信息）有什么方式吗？

### ISSUE THREAD

**Issue by fengchen8556203** [sjqzhang/go-fastdfs#437]
您好：
         正如题目中所说的，只有在第一次上传文件后可以返回一个json信息，是否可以有方式查看历史文件或者所有文件的上传后返回的json信息呢？

**Comment by sjqzhang** [comment]
无法查询，除非自已写代码查数据库。
