### ISSUE TITLE
如何添加白名单

### ISSUE THREAD

**Issue by mapeiran** [sjqzhang/go-fastdfs#438]
配置的gofastdfs的ip和端口，在默认情况下直接访问http://ip:port会返回web upload deny字样，现在想要禁止这种访问形式，只允许访问对应的下载路径，应该怎么解决

**Comment by sjqzhang** [comment]
看视频教程

**Comment by mapeiran** [comment]
> 看视频教程

三个视频都看了，没找到白名单怎么添加
