### ISSUE TITLE
在没有高速缓存的情况下，tmp缓存目录是不是价值不大？

### ISSUE THREAD

**Issue by LiyuLiu8270** [sjqzhang/go-fastdfs#443]
由于有tmp目录存在，缓存和持久存储都在同一块磁盘，反而增加了一倍的IO开销，降低了磁盘性能。
在应对超过持续时长可能超过7*24小时的100QPS纯图片上传请求场景下，如果没有SSD高速缓存，我们去除这个逻辑是否会更好一些？

**Comment by sjqzhang** [comment]
没有临时目录，存在内存占用高甚至溢出等问题，可以自已想办法增加高速缓存。linux  tmpfs就可以使用
