### ISSUE TITLE
是否完全兼容原版fastdfs的协议和用法

### ISSUE THREAD

**Issue by Faputa** [sjqzhang/go-fastdfs#446]
原版的fastdfs部署太麻烦，想用go-fastdfs替换掉，但是不知道本项目是否完全兼容原版fastdfs的协议和用法

**Comment by sjqzhang** [comment]
这个与C版本的fastdfs完全不是一个东西，只是思想上有相似的地方，正是因为C版本的太复杂，为了简化安装运维等才有go-fastdfs，同时也有很多特性是c版本的fastdfs没有的，建议使用前先看一下目档或文档路径中的视频教程。
