### ISSUE TITLE
压测过程中kill -9某个节点模拟宕机，后续集群其他节点文件句柄数飙升，最后cpu打满，直接崩溃不可用

### ISSUE THREAD

**Issue by nwpuqyj** [sjqzhang/go-fastdfs#449]
我们采用的是1.4.3版本，总共6个节点。

生产环境某个节点宕机后，比较频繁地出现文件句柄数过多，cpu飙升的情况。后续在测试环境压测复现该情况，发现句柄集中在向宕机节点同步数据的tcp请求上。

恢复该宕机节点依旧解决不了其他节点句柄数飙升的问题（linux、fileserver的句柄数上限均为65535），我们只能全部停掉所有节点，然后全部重启。但所有节点重启后句柄数飙升，基于nginx反向代理进行文件上传后，在日志中发现上传的节点不再向其他5个节点同步文件，且一段时间后，fileserver.log文件报出以下ERR内容：

[fileserver.go:454] [(*Server).postFileToPeer] Post "http://集群其他节点ip:8080/group1/syncfile_info": read tcp 当前节点ip:39896->其他节点ip:8080 i/o timeout

**Comment by sjqzhang** [comment]
还有现场么？加我微信让我远程看看
