### ISSUE TITLE
是否支持文件加密

### ISSUE THREAD

**Issue by xu8117** [sjqzhang/go-fastdfs#450]
未授权用户在直接访问文件系统的 “files” 文件夹时，依旧能够获取其中的文件。因此想了解系统是否支持对上传文件进行加密处理，如此一来，即便未授权用户通过非法手段破解了访问限制，所能获取到的也仅仅是加密文件，从而保障文件原始内容的安全。

**Comment by sjqzhang** [comment]
暂不支持对上传文件加密，考虑到系统性能问题短期内也不打算增加相关特性，可以考查一下别的文件系统是否支持。
