### ISSUE TITLE
auth_url这个有问题，会有缓存，请求一次回来的认证会保存大概1分钟，是个bug

### ISSUE THREAD

**Issue by ztfcharlie** [sjqzhang/go-fastdfs#451]
"认证url": "当url不为空时生效,注意:普通上传中使用http参数 auth_token 作为认证参数, 在断点续传中通过HTTP头Upload-Metadata中的auth_token作为认证参数,认证流程参考认证架构图", 	
"auth_url": "http://172.19.7.2:8080/security",

bug表现，这个验证不是每一次上传都去验证的。这是个明显的bug；
复现，先http://172.19.7.2:8080/security返回ok，第一次上传成功了。然后马上把返回值改成failed，再上传另外一个文件，居然成功了。这里的成功时间大概持续1分钟，都能成功。
导致的严重错误：如果一个用户刚刚上传成功，另外一个用户，不需要认证，都可以往接口提交上传，如果我找到了提交上传的地址，启动一个大循环，就等一个有人上传成功的机会，等到以后，大量上传文件，磁盘两下满了，game over。

**Comment by sjqzhang** [comment]
参考内置的上传页面，将auth-token放到http头中，验证代码参考 auth.py文件
