### ISSUE TITLE
是否可以和阿里云oss一样，作为一个静态文件服务器提供静态网页

### ISSUE THREAD

**Issue by zhuxiujia** [sjqzhang/go-fastdfs#48]
是否可以和阿里云oss一样，作为一个静态文件服务器提供静态网页。
例如阿里云oss，可以直接用vuejs打包好的静态资源（dist/css/image）上传上去，浏览器打开即可为网站显示出来

**Comment by sjqzhang** [comment]
是可以的，就是自定义路径
