### ISSUE TITLE
定时同步的问题

### ISSUE THREAD

**Issue by chengyuansen** [sjqzhang/go-fastdfs#5]
看您文档的描述，多服务器之间的文件同步不是实时的，而是每小时同步一次。这会造成一个问题就是当我通过nginx负载均衡访问一个文件的时候，正好这个文件所在的服务器宕机了，但这个文件还没有来得及同步到别的机器上，那么这个文件就无法访问到，也无法通过访问文件的方式实现自动同步，因为源文件服务器挂了。这样可用性就会降低。
各文件服务器间能否通过异步方式实现数据同步呢？当然这样肯定性能会有所损失。

**Comment by sjqzhang** [comment]
集群的机器只要在线，文件同步是实时的，而且默认会在两分钟内对异常文件进行自动同步，每小时同步一次，指的是按天检查文件的数量是否一致，你用最新的版本再试一下，我已经对极端的情况都进行过压测了，你可以体验一下。
