### ISSUE TITLE
java client InputStream的问题

### ISSUE THREAD

**Issue by sunnyleixu** [sjqzhang/go-fastdfs#54]
在使用java版的客户端上传文件时，如果是文件流的话，怎么上传？
或者是Base64转码后的图片怎么上传？

**Comment by sjqzhang** [comment]
在开源中国有文章介绍，搜一下，后面会加入wiki中

**Comment by zhangdachen** [comment]
> 在开源中国有文章介绍，搜一下，后面会加入wiki中

请问这个文章链接多少，没有搜到
