### ISSUE TITLE
上传文件重名覆盖问题

### ISSUE THREAD

**Issue by liupengpop** [sjqzhang/go-fastdfs#57]
上传文件时，同一分钟上传文件如果文件名重复了，文件就直接覆盖。有没有好的方法解决。

**Comment by liupengpop** [comment]
在关闭 文件是否去重 之后会出现这种情况

**Comment by sjqzhang** [comment]
这应该不是问题,应该是特性

**Comment by happyangel621** [comment]
这个问题我也发现了，在两种场景下会出现。
1. 如果两次上传两个文件，两个文件同名（内容不同），由于两次上传间隔时间很短，会出现上传至通一个文件夹下，这种情况后上传的会覆盖先上传的，这个问题是操作系统在通一个文件夹下不会出现同名文件造成的。
2. 如果自定义上传路径，上传两个同名文件，只会保留一个。也是操操作系统在通一个文件夹下不会出现同名文件造成的。

这两种情况可以通过打开重名选项打开，即可解决。
![image](https://user-images.githubusercontent.com/12292814/58786593-8333ea00-861a-11e9-9875-eee46dd706a5.png)

如果可以建议作者把这两种情况在wiki上做一下说明。另外，在有些场景下需要保留原文件名，为了防止覆盖是否可以考虑加上在同一文件夹下上传两个同名文件添加文件名前缀/后缀，或自定义前后缀的功能。 由于太喜欢这个程序，希望作者能做的越来越好，只是建议，无意冒犯。
