### ISSUE TITLE
有时候会产生没有文件实体的空文件夹

### ISSUE THREAD

**Issue by chengyuansen** [sjqzhang/go-fastdfs#6]
往由2台服务器构成的集群的其中一台上传文件，上传完毕后由于MD5值相同（但文件内容不同），没有实际上传文件只是直接返回了已经上传完毕的相同MD5的文件路径。但这时产生了一个空文件夹，里面没有文件实体。上传过程中遇到过2次这种情况。过一段时间空文件夹被自动清除。

**Comment by sjqzhang** [comment]
这是预期之内，是设计的正常逻辑，请放心，这不是bug
