### ISSUE TITLE
上传文件返回值的问题

### ISSUE THREAD

**Issue by chengjianxi** [sjqzhang/go-fastdfs#60]
下面的问题主要是针对文件上传的：

1. 我个人觉得在 `Upload(...)` 函数中应该先判断`output`参数的值。现在的问题时上传文件时指定参数`output`为json时，如果发生错误，返回的格式有的时候还是文本。

2.上传文件发生错误时，靠什么判断是否上传成功？例如参数错误时http的返回值是200，无论是指定的 `output`为json还是`text` 上传文件错误都没有错误码返回 

3.这个是针对`output`为json来说的，我发现FileResult.Retcode的这个值没有被使用过，也就是说无论上传成功还是失败，retcode的返回值都是0。
我测试了秒传，当文件不存在时retcode的返回值确实是0，http的返回值是200。
我们更偏向使用json来解析上传结果，因为json对程序开发来说更友好一些

**Comment by sjqzhang** [comment]
用最新版本试一下

**Comment by chengjianxi** [comment]
说的就是最新版的问题啊

**Comment by chengjianxi** [comment]
> 用最新版本试一下

说的就是最新版的问题啊
