### ISSUE TITLE
> 启动时设定环境变量

### ISSUE THREAD

**Issue by 852675742** [sjqzhang/go-fastdfs#62]
> 启动时设定环境变量

在启动时指定了环境变量，会重新生成配置文件等信息，这样的话是不是我如果之前在另外一个路径上存有文件的话，是不是就无法访问了呢比如：开始在甲路径上存放文件，后来改到了乙路径。此时使用的是乙路径下的配置文件，这时候是不是就没有办法再访问到甲下面的文件了呢

_Originally posted by @xiangshibo in https://github.com/sjqzhang/go-fastdfs/issues/34#issuecomment-481144561_

**Comment by sjqzhang** [comment]
是的，文件路径是不能随便变的，可以将以前的文件复制到新的文件路上下，然后开启文件迁移功能实现文件元数据修复。注意:不是修复功能！是迁移功能！

**Comment by 852675742** [comment]
谢谢大佬的耐心解答，后续测试验证一下。


------------------ 原始邮件 ------------------
发件人: "小张"<notifications@github.com>;
发送时间: 2019年5月27日(星期一) 晚上9:37
收件人: "sjqzhang/go-fastdfs"<go-fastdfs@noreply.github.com>;
抄送: "张春林"<852675742@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sjqzhang/go-fastdfs] > 启动时设定环境变量 (#62)




是的，文件路径是不能随便变的，可以将以前的文件复制到新的文件路上下，然后开启文件迁移功能实现文件元数据修复。注意:不是修复功能！是迁移功能！
