### ISSUE TITLE
Deploy with Caddy instead of Nginx?

### ISSUE THREAD

**Issue by keyeMyria** [sjqzhang/go-fastdfs#64]
Any examples for deployment with [Caddy](https://github.com/mholt/caddy) instead of Nginx?

**Comment by sjqzhang** [comment]
我不熟悉Caddy，希望你可以参考nginx配置编写caddy配置并写入到项目的wiki中

I am not familiar with Caddy, I hope you can refer to nginx configuration to write caddy configuration and write it into the wiki of the project.
