### ISSUE TITLE
集群环境下未开启文件去重统计信息收集错误

### ISSUE THREAD

**Issue by happyangel621** [sjqzhang/go-fastdfs#67]
不确认是否是bug，请作者确认。
![image](https://user-images.githubusercontent.com/12292814/58692239-ca26a300-83c0-11e9-9000-39f65068cd4e.png)
同样的文件上传了三次
![image](https://user-images.githubusercontent.com/12292814/58692292-e3c7ea80-83c0-11e9-9f39-f2fb98828416.png)
统计信息只有一个文件
![image](https://user-images.githubusercontent.com/12292814/58692320-f7735100-83c0-11e9-8344-62be395d0343.png)

根据wiki说明，删除了data/stat.json, 重启服务后统计信息相同。

**Comment by sjqzhang** [comment]
应该是bug,下版本修证一下
