### ISSUE TITLE
集群环境下关闭文件去重，文件不同步

### ISSUE THREAD

**Issue by happyangel621** [sjqzhang/go-fastdfs#68]
测试环境1.3.0
![image](https://user-images.githubusercontent.com/12292814/58941470-6f20f180-87ae-11e9-8192-0a05f6367b6d.png)
![image](https://user-images.githubusercontent.com/12292814/58941500-84961b80-87ae-11e9-8b24-d178822cecf6.png)
关闭文件去重
![image](https://user-images.githubusercontent.com/12292814/58941566-a68f9e00-87ae-11e9-9088-1463cf718159.png)
通过nginx上传文件成功
![image](https://user-images.githubusercontent.com/12292814/58941650-ca52e400-87ae-11e9-8325-89b18ecad532.png)
查看磁盘，一台机器有，另外一台机器没有
![image](https://user-images.githubusercontent.com/12292814/58941742-f66e6500-87ae-11e9-9b49-98e53f7ecd58.png)
![image](https://user-images.githubusercontent.com/12292814/58941753-fd957300-87ae-11e9-9876-ff3a1cae1860.png)

开启文件去重
![image](https://user-images.githubusercontent.com/12292814/58941828-23bb1300-87af-11e9-8b30-69356b50c63a.png)
重启服务后
文件同步正常

**Comment by sjqzhang** [comment]
已修复
