### ISSUE TITLE
代码质量太垃圾，捏着鼻子先用, 主程加油！

### ISSUE THREAD

**Issue by west-wind-luwei** [sjqzhang/go-fastdfs#69]
##### 单词拼写错误：alram是什么东东？
```json
"alram_receivers": [],
"alarm_url": "",
```

##### 配置文件注释写了个半吊子，看上去文字挺多，但还得看代码才能彻底搞明白
```json
"是否支持web上传,方便调试": "默认支持web上传",
"enable_web_upload": true,
"是否支持非日期路径": "默认支持非日期路径,也即支持自定义路径,需要上传文件时指定path",
"enable_custom_path": true,
"下载域名": "用于外网下载文件的域名,不包含http://",
"download_domain": "",
"场景列表": "当设定后，用户指的场景必项在列表中，默认不做限制(注意：如果想开启场景认功能，格式如下：'场景名:googleauth_secret' 如 default:N7IET373HB2C5M6D ",
"scenes": []
```
这样的注释就是字面义翻译而已，你不加注释我也能猜出来。
就说场景，是个字符串数组，可是我具体如何使用呢，和文件路径或分组有关系吗？应该加个具体使用说明或参见。

#### 2 代码中的注释少的可怜
另外, 一个文件3700多行，你不会拆几个文件吗？

#### 3 返回格式不统一
说好统一为：
```json
{"data": "", "message": "", "status": "ok"}
```
结果upload和check_file_exist都不是

#### 4 命名格式不统一
mtime, timeStamp, is_dir 小写、驼峰和下划线混用

#### 5 数值格式不统一
```json
"mtime":1560116434
"mtime": "2019-06-10T05:25:03.269233322+08:00"
"timeStamp": 1560116434
```
mtime和timeStamp相等又是几个意思？

#### 6 check_file_exist接口只有md5参数，为什么不支持filePath？
比较反人类

#### 7 组号功能无论是否启用支持按组管理都会影响路径，并且接口对组号的处理不一致
默认情况下：文件下载和get_file_info接口都需要组号，而upload和check_file_exist却不需要组号

#### 8 API接口文档太简陋了
既然开源，那么写代码、写文档就要高标准、高要求，站在全局角度多考虑一下，不要犯普通程序员通病。

**Comment by west-wind-luwei** [comment]
由is_dir导致丑陋的代码
public class ListBean {
	private boolean is_dir;
	private String md5;
	private String mtime;
	private String name;
	private String path;
	private Long size;

	public boolean isIs_dir() {
		return is_dir;
	}

	public void setIs_dir(boolean is_dir) {
		this.is_dir = is_dir;
	}

**Comment by sjqzhang** [comment]
这个项目需要你的支持，希望你能优化一下代码提交合并请求，我来合并，如果单纯是抱怨没有实际贡献，也希望你不要用这个项目，坑你没商量^_^

**Comment by pkaq** [comment]
文档确实是.........一言难尽啊
