### ISSUE TITLE
文件服务器是怎样扩容的？

### ISSUE THREAD

**Issue by chengyuansen** [sjqzhang/go-fastdfs#7]
文件服务器的扩容是怎样实现的呢？比如现在已经配置了三个peer节点，这三个节点对等，会自动同步文件，实现了文件服务器的高可用。但发现有一天文件服务器磁盘快满了，我应该怎样扩容呢？
扩容方案：
1）增加服务器，新增加的服务器跟现有peer节点之间数据不再同步，而是跟现有peer节点间形成2个分片式集群。也就是可以形成多个分片，每个分片数据都不相同，每个分片都可以有多个对等节点，形成高可用。这种实现方式有点类似于solr。
2）在现有节点上挂载新空间。利用存量对等节点，给每个节点都分配新的存储空间。这种方式有点类似于TFS。

**Comment by sjqzhang** [comment]
建议三台一组，三台一组，组成一个集群。

如果是增加机器，加入新机器后按FAQ说明，访问集群修复链接即可完成同步，建议低峰进行操作。

如：http://10.10.10.x:8080/repair
注意要在集群机器上访问

**Comment by chengyuansen** [comment]
我想问的是文件服务器本身是怎样实现扩容的。如果只是加入新机器，那么对存量机而言，仅仅是多了一个副本而已，达不到扩容的目的啊，只是可用性提高了而已。您能说明下具体怎么扩容吗？

**Comment by sjqzhang** [comment]
你说得对，增加新机器，只会增加副本数，没增加容量，如果要扩容就增加集群或者增加硬盘容量。

**Comment by chengyuansen** [comment]
建立文件服务器集群时一般都会使用大容量硬盘，但最开始评估的时候其实并不知道业务的文件增量会是多少，也不知道文件会增加到什么程度，所以即便开始使用大容量硬盘可能最终还是经不住日积月累的累积。能不能在设计这个系统的时候可以在运行中动态增加系统容量呢？比如我看到有个参数：group，我不知道这个参数目前有什么用途，但可以采用类似group的概念组成一个大集群，同一个group服务器间文件同步以提高可用性，不同group之间不同步，增加集群容量。这样最开始建立服务器集群的时候只需要三台服务器，设置一个group，这三天服务器之间文件同步。运行过程中如果容量不够了，可以动态修改配置，通过增加不同的group来扩容。

**Comment by sjqzhang** [comment]
这个理论可以实现，但从无论从代码逻辑还是运维都增加不少复杂度，很易引发副本同步等问题，基于这些考虑，暂时先不增加这种动态扩容方式。

**Comment by chengyuansen** [comment]
也就是说目前一旦文件服务器容量确定之后，后期没用办法扩容对吧。

**Comment by sjqzhang** [comment]
目前是这样的，如果前期做好逻辑卷lvm 通过增加磁盘也是可以的，只是没动态扩容来得方便。

**Comment by foooy** [comment]
现在扩容方式 ，感觉不太好

**Comment by liumuqi** [comment]
那这还叫什么分布式文件系统。就是个带备份有http功能的ftp服务。。。。。。
