### ISSUE TITLE
图片上传scene字段设置无效

### ISSUE THREAD

**Issue by AKcheng** [sjqzhang/go-fastdfs#72]
上传文件不是图片时scene字段设置是有效的，当上传文件为图片时，会使用图片后缀作为场景，即使设置的scene字段也无效

**Comment by sjqzhang** [comment]
这应该不是官方支持的，应该是从别的地方下载的版本，这得你自行解决

**Comment by AKcheng** [comment]
绝对是官方下载版本，5月份时候下载的，刚开始提问题时我就想，作者会不会回复我请下载新版本，不过你这个回答有过子而无不及，我下个新版本试试算了
