### ISSUE TITLE
怎么防止恶意上传耗尽磁盘空间

### ISSUE THREAD

**Issue by huashiyiqike** [sjqzhang/go-fastdfs#73]
上传链接固定，怎么防止被恶意利用呢

**Comment by huashiyiqike** [comment]
群里有人提出一个好办法
没有业务价值的文件就删除，我举个例子，比如 我有个表单，里面有合同上传，文件是异步上传到文件服务器然后返回文件id的,然后这个人一直上传 就是不提交表单，那么它上传的这个合同文件是不是没有任何价值 然后你上传文件不是给你返回 文件信息吗，你在你项目创建个数据库 文件表，加一个状态，状态分别有，零时文件 ，正式文件，然后异步上传的文件统统是 零时文件状态，只有这个表单提交后，再去改这个状态为正式文件，然后开个任务调度器，根据数据库查询一天前的零时数据，循环删除
如果开启小文件合并功能，后期是无法删除小文件的。
需要提供删除接口，根据业务清除没有意义的上传数据

**Comment by sjqzhang** [comment]
这个业务去控制好点，文件系统如果干太多业务相关的事，性能，维护等都不是特别好
