### ISSUE TITLE
多次重复提交有概率不能上传成功

### ISSUE THREAD

**Issue by JiangJiaqi90** [sjqzhang/go-fastdfs#76]
关闭了文件去重 ，上传同一个文件，生成文件唯一名称，按一定散列算法生成目录，多次重复上传，怎么有时也返回之前目录的文件，文件名也不对。。。
关键是文件保存也不成功
![image](https://user-images.githubusercontent.com/44488028/60080654-e79e2100-9762-11e9-8652-eba83a38e5c8.png)

**Comment by sjqzhang** [comment]
你检查一下你的应用，感觉是你应用本身问题。
