### ISSUE TITLE
断点续传文件保存在服务器什么位置？

### ISSUE THREAD

**Issue by githubkevinyou** [sjqzhang/go-fastdfs#79]
通过tus上传示例，url改成 http://xxx/group1/big/upload，上传成功后返回http://xxx/group1/big/upload/ae5fe8c87bd969fc7eeefb21e894663c，可以通过浏览，但是服务器中找不到保存位置，想以后迁移会有问题

**Comment by sjqzhang** [comment]
上传后，要转换真实地址，真实地址里包含文件的路径，正确使用断点续传功能，可以参考wiki说明。

**Comment by githubkevinyou** [comment]
文件id：ae5fe8c87bd969fc7eeefb21e894663c 通过什么算法转换真实地址的？
