### ISSUE TITLE
Nginx反向代理大文件不能分片上传

### ISSUE THREAD

**Issue by mopoliujia** [sjqzhang/go-fastdfs#80]
nginx反向代理后，大文件上传不能分片上传。上传过程中，暂停后重新启动有会重新上传

**Comment by sjqzhang** [comment]
参考项目中nginx 配置

**Comment by lwj-java** [comment]
> nginx反向代理后，大文件上传不能分片上传。上传过程中，暂停后重新启动有会重新上传

请问您这边解决了嘛？

**Comment by lwj-java** [comment]
> 参考项目中nginx 配置

使用的就是项目中nginx配置，还是不行，我观察，_big文件夹并没有生成-lock文件，导致暂停的时候，文件没有写入，重新启动时候，就没法断点续传了。

**Comment by lwj-java** [comment]
> nginx反向代理后，大文件上传不能分片上传。上传过程中，暂停后重新启动有会重新上传

nginx要增加如下配置:  proxy_request_buffering  off; proxy_buffering          off;  , 防止nginx给你buffer了， 就导致tusd一直没有收到相关文件流。
