### ISSUE TITLE
删除文件权限问题

### ISSUE THREAD

**Issue by 852675742** [sjqzhang/go-fastdfs#82]
我现在是在gofastdfs前面安装了nginx，由于我上传返回了文件上传地址给前端，如果知道是使用了gofastdfs的话可以调用gofastdfs delete接口删除文件，怎么解决这个直接调用delete接口的问题导致乱删除，即权限问题，因为gofastdfs现在配置的admin_ips是nginx的ip地址，请指导一下。

**Comment by sjqzhang** [comment]
通过获取真实ip进行区分，可以自行测试一下

**Comment by 852675742** [comment]
> 通过获取真实ip进行区分，可以自行测试一下

即使我程序还是外部利用postman调用，都是直接调用nginx的那个接口地址，没有直接经过gofastdfs的服务地址，通过真实ip怎么区分啊？是在nginx层做处理吗？
