### ISSUE TITLE
同一主机上运行两个不同配置的fileserver会有冲突吗？

### ISSUE THREAD

**Issue by jackeylu** [sjqzhang/go-fastdfs#85]
我的场景是这样的：
1. 对内，我希望快速简单地支持文件上传（不想建一个第三方鉴权服务）
2. 对外，我希望下载方只要获取到URL就可以直接下载，不需要鉴权。

我打算这样做：一台服务器上跑两个fileserver，分别用于上传和只读下载。这意味着要两个fileserver共享一个file目录，但使用不同的配置文件。

请问这样使用会有什么问题没有考虑吗？

感谢！

**Comment by sjqzhang** [comment]
没这么用过，可以能做也可以不能做，软链接或nginx都可以，具体你自己想想办法去试一下。
