### ISSUE TITLE
线上环境为什么不建议用容器部署

### ISSUE THREAD

**Issue by Jrohy** [sjqzhang/go-fastdfs#86]
![image](https://user-images.githubusercontent.com/12463263/61199261-dcaa3100-a70f-11e9-9058-b2fa16ca53cf.png)
最佳实践为什么不推荐正式环境用容器部署，容器部署又能设置开机自启，重启也方便。 假如说是因为改配置不方便的话，整个操作目录-v绑定也行， 想不通什么理由不推荐容器部署😂

**Comment by sjqzhang** [comment]
容器挂载方式，性能及稳定性没有在生线环境上验证过，你可以给大家提供案例^_^
