### ISSUE TITLE
断点上传excel文件之后，下载的文件错误

### ISSUE THREAD

**Issue by 1692737734** [sjqzhang/go-fastdfs#89]
断点上传excel文件之后，下载的文件错误

**Comment by sjqzhang** [comment]
是项目自还的，还是你自己封装的？

**Comment by 1692737734** [comment]
> 是项目自还的，还是你自己封装的？

自己通过java封装了一下，但是下载使用的是断点上传返回的地址，然后使用了项目里的上传的页面尝试也产生了错误，版本是最新的
