### ISSUE TITLE
后续会支持分块上传，断点续传么？

### ISSUE THREAD

**Issue by vinsonzou** [sjqzhang/go-fastdfs#9]

**Comment by sjqzhang** [comment]
断点续传需要单独开发客户端，设计及使用都不是很方便 ，“大道至简”也是本方案与c版本的fastdfs最大区别之一，而且现在的网络都相对较快，文件如果不是特别大的话，没有这个必要，所以暂时没计划加入断点续传。如果你感兴趣也可以fork一个增加这特性，我合并进去。

**Comment by eva00rei00** [comment]
哪请问分块上传功能会有么? @sjqzhang

**Comment by sjqzhang** [comment]
目前是不支持的，你的需求是上传大文件要分块上传么？ 这种要客户端的支持感觉使用上不是很方便。

**Comment by sjqzhang** [comment]
这样删会有风险，除非你后面不会上传同样的文件，因为单删除文件还有元数据没删

**Comment by sjqzhang** [comment]
已支持断点续传。（tus）
