### ISSUE TITLE
windows 多用户登陆,程序会意外退出

### ISSUE THREAD

**Issue by luchatex** [sjqzhang/go-fastdfs#90]
很棒的文件服务器!
但在windows server系统(别问为何要用win,不是我决定的) 启动后,当有另外用户远程会造成意外退出.频繁的.

**Comment by luchatex** [comment]
win希望添加可以注册成服务的功能

**Comment by sjqzhang** [comment]
对windows 不熟悉，表示帮不了，自行查阅资料解决。

**Comment by lhtdeg** [comment]
可以通过nssm自行注册成服务
