### ISSUE TITLE
一次请求是否可以上传多个文件

### ISSUE THREAD

**Issue by lhtdeg** [sjqzhang/go-fastdfs#91]
http请求的form-data格式一个key是可以上传多个文件的，有没有考虑增加这个功能，返回一个地址的list?

**Comment by sjqzhang** [comment]
开源版本暂时不支持，你如果有这种需求，可以自行实现，最好还能提交一个合并请求。

**Comment by worldofchu** [comment]
收费版本？哪里获取怎么收费的？收费版本有这个功能吗
