### ISSUE TITLE
http响应数据格式不统一

### ISSUE THREAD

**Issue by kaiouz** [sjqzhang/go-fastdfs#94]
1. upload接口指定output=json时,发生错误时返回的数据根本不是json
2. output=json时http响应的conetnt-type不是application/json
3. 希望返回结果具有一致的格式，上传完成时无法方便确认是否成功，因为失败了http状态码仍然是200

**Comment by sjqzhang** [comment]
请使用最新版本测试，业务错误建不要使用http状态码表示，可以通过返值进行判断
