### ISSUE TITLE
断点续传怎么获取上传后的访问路径

### ISSUE THREAD

**Issue by kaiouz** [sjqzhang/go-fastdfs#95]
1. 普通上传后会返回的是FileResult，与其它接口不一致，其它接口会用JsonResult包装一下, 返回json数据时，响应的Content-Type不是application/json
2. 断点续传后怎么获取访问路径？普通上传后可以从FileResult中path字段获取，断点续传通过文件ID只能获取FileInfo然而FileInfo中的path字段和FileResult的path不一样,FileInfo中的path不是真正的访问路径, 如果通过替换和拼接FileInfo的path来获取访问路径的话, 缺少group信息。以下是两者区别:
```javascript
// FileResult
{
    "url": "http://192.168.15.6:8081/group1/default/20190731/10/21/0/DSC_3100.JPG",
    "md5": "c0ef54308618b29a4115d4fff9bb6398",
    "path": "/group1/default/20190731/10/21/0/DSC_3100.JPG",
    "domain": "http://192.168.15.6:8081",
    "scene": "default",
    "size": 80381,
    "mtime": 1564539679,
    "scenes": "default",
    "retmsg": "",
    "retcode": 0,
    "src": "/group1/default/20190731/10/21/0/DSC_3100.JPG"
}
// FileInfo
{
    "name": "DSC_3100.JPG",
    "rename": "",
    "path": "files/default/20190731/10/21/0",
    "md5": "c0ef54308618b29a4115d4fff9bb6398",
    "size": 80381,
    "peers": [
        "http://192.168.15.6:8081"
    ],
    "scene": "default",
    "timeStamp": 1564539679,
    "offset": -1
}
```

**Comment by sjqzhang** [comment]
因为历史兼容问题造成，请自行兼容

**Comment by lwj-java** [comment]
> 1. 普通上传后会返回的是FileResult，与其它接口不一致，其它接口会用JsonResult包装一下, 返回json数据时，响应的Content-Type不是application/json
> 2. 断点续传后怎么获取访问路径？普通上传后可以从FileResult中path字段获取，断点续传通过文件ID只能获取FileInfo然而FileInfo中的path字段和FileResult的path不一样,FileInfo中的path不是真正的访问路径, 如果通过替换和拼接FileInfo的path来获取访问路径的话, 缺少group信息。以下是两者区别:
> 
> ```js
> // FileResult
> {
>     "url": "http://192.168.15.6:8081/group1/default/20190731/10/21/0/DSC_3100.JPG",
>     "md5": "c0ef54308618b29a4115d4fff9bb6398",
>     "path": "/group1/default/20190731/10/21/0/DSC_3100.JPG",
>     "domain": "http://192.168.15.6:8081",
>     "scene": "default",
>     "size": 80381,
>     "mtime": 1564539679,
>     "scenes": "default",
>     "retmsg": "",
>     "retcode": 0,
>     "src": "/group1/default/20190731/10/21/0/DSC_3100.JPG"
> }
> // FileInfo
> {
>     "name": "DSC_3100.JPG",
>     "rename": "",
>     "path": "files/default/20190731/10/21/0",
>     "md5": "c0ef54308618b29a4115d4fff9bb6398",
>     "size": 80381,
>     "peers": [
>         "http://192.168.15.6:8081"
>     ],
>     "scene": "default",
>     "timeStamp": 1564539679,
>     "offset": -1
> }
> ```

请问断点续传后，文件ID在哪里，使用示例上传后，哪个是文件ID啊
![image](https://user-images.githubusercontent.com/17963538/108808244-25f77d80-75e1-11eb-9ba8-bf24106ee359.png)
