### ISSUE TITLE
auth_token校验后返回值问题

### ISSUE THREAD

**Issue by xinxin88o** [sjqzhang/go-fastdfs#96]
作者您好：
        我想问下在进行token验证时候，go-fastdfs 能否将鉴权应用服务返回的报文透传回来。
目前使用1.3.1gofastdfs 版本测试时候， 发现鉴权服务那边不管返回什么报文，只要不是ok ，gofastdfs都是报auth fail，  这样感觉授权给别人使用的时候， 不怎么友好性。  在使用时候，对方不知道是因为什么原因导致token校验失败。

**Comment by sjqzhang** [comment]
开源版本不支持。
