### ISSUE TITLE
用非本地IP访问search路由会提示权限问题但是依然会返回数据

### ISSUE THREAD

**Issue by kinterq** [sjqzhang/go-fastdfs#97]
使用的是源码中提供的nginx的配置，nginx做反向代理的,请问这个是原本就是这样设计的吗。
![image](https://user-images.githubusercontent.com/30406499/62401271-08a12f80-b5b5-11e9-9c42-c6f160cb6020.png)
但是如果访问list_dir的时候是正常的拒绝返回数据
![image](https://user-images.githubusercontent.com/30406499/62401403-9f6dec00-b5b5-11e9-8e54-18670ff95c2b.png)
还有status这些路由为什么可以不受权限控制的任意可以访问呢。我用非本地ip也可以查看这些。后台的这些接口不应该不受控制的可以任意查看吧
![image](https://user-images.githubusercontent.com/30406499/62401538-39359900-b5b6-11e9-8c5b-9ddd88f695cf.png)

**Comment by sjqzhang** [comment]
第一个应该是BUG，下次发版修复，第二个不对集群以外的IP开放读权限，如需要自行修改
